/*
 * Code generated by lginterop -primitives; DO NOT EDIT.
 */

package corefns

import (
	"github.com/nooga/let-go/pkg/rt"
)

func RegisterGeneratedPrimitives() {
	rt.RegisterNativeModule(&rt.NativeModule{
		GoPkg:     "github.com/nooga/let-go/pkg/rt/corefns",
		Namespace: "clojure.core",
		Fns: map[string]rt.NativeDirectFn{
			"seq":    {GoIdent: "Seq", LgName: "seq", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"first":  {GoIdent: "First", LgName: "first", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"second": {GoIdent: "Second", LgName: "second", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"next":   {GoIdent: "Next", LgName: "next", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"rest":   {GoIdent: "Rest", LgName: "rest", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"count":  {GoIdent: "Count", LgName: "count", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
		},
	})
}

func init() {
	RegisterGeneratedPrimitives()
}
