# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetGo < Formula
  desc "A Clojure dialect implemented as a bytecode VM in Go"
  homepage "https://github.com/nooga/let-go"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_2.0.2_darwin_amd64.tar.gz"
      sha256 "0836582b45814611e7a1c1bfc6b06aabfa4b7c6a7b6028c02f8926a361998a7d"

      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_2.0.2_darwin_arm64.tar.gz"
      sha256 "be0a3c8cdc64225e581cb37807f241daebef480101f771d938aa4a1ca734f8f2"

      define_method(:install) do
        bin.install "lg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_2.0.2_linux_amd64.tar.gz"
      sha256 "1d23d8b599c63f8c1f16a2d5150519034065c04859f4da3121748c95749e6c20"
      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_2.0.2_linux_arm64.tar.gz"
      sha256 "57a80c1f5e57e308b4e95200c3b8e60a0322824ad8871fe2a23e1d44f8cee77d"
      define_method(:install) do
        bin.install "lg"
      end
    end
  end

  test do
    system bin/"lg", "-e", "(+ 1 1)"
  end
end
