/*
 * Copyright (c) 2026 Norman Nunley, Jr <nnunley@gmail.com>
 * Part of the let-go project; see CONTRIBUTORS for full list of authors.
 * SPDX-License-Identifier: MIT
 */

// Provenance dependency manifest: which generator INPUTS feed each generated
// OUTPUT, plus exact readiness hashes for declared file outputs. `make generate`
// reruns stages when inputs change or recorded output bytes are disturbed.
// Content-based (sha256), never mtime — checkout-safe.
package genmanifest

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Edge is one (output, input, kind) manifest relation. Kind is "input" (a
// domain source), "generator" (generator implementation), or "output" (the
// declared file output's last generated bytes). Edges returns only the first
// two kinds; output records are added when the manifest is written.
type Edge struct {
	Output string
	Input  string
	Kind   string
}

// DepManifestRelPath is the committed manifest, co-located with generated.sums.
const DepManifestRelPath = "pkg/rt/generated.manifest"

type sweep struct{ dir, ext string }

// outputSpec declares one generated output and how to find its inputs. A sweep
// walks dir for *.ext (skipping generated + _test.go for input sweeps); files
// are explicit paths; genPackagePattern selects generator inputs via the Go tool.
type outputSpec struct {
	output            string
	inputSweeps       []sweep
	inputFiles        []string
	genSweeps         []sweep
	genFiles          []string
	genPackagePattern string
	genBuildTags      []string
}

// goListPackage contains every selected source/native/embed file group from
// `go list -json`. Files excluded by build constraints are deliberately absent.
type goListPackage struct {
	Dir    string
	Module *struct {
		Main bool
		Path string
	}
	GoFiles      []string
	CgoFiles     []string
	CFiles       []string
	CXXFiles     []string
	MFiles       []string
	HFiles       []string
	FFiles       []string
	SFiles       []string
	SwigFiles    []string
	SwigCXXFiles []string
	SysoFiles    []string
	EmbedFiles   []string
}

func isEphemeralBackup(path string) bool {
	lower := strings.ToLower(path)
	for _, suffix := range []string{"~", ".bak", ".backup", ".orig", ".rej", ".swp", ".tmp"} {
		if strings.HasSuffix(lower, suffix) {
			return true
		}
	}
	return false
}

// goModuleBuildInputs asks the Go tool for the canonical main-module package
// closure, then records every non-test build source in those package directories.
// Following imports from all Go variants makes the result a stable superset of
// the files that can build lgbgen on any host, rather than a Linux-only graph.
func goModuleBuildInputs(repoRoot, packagePattern string, buildTags ...string) ([]string, error) {
	root, err := filepath.Abs(repoRoot)
	if err != nil {
		return nil, fmt.Errorf("resolve repository root %q: %w", repoRoot, err)
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return nil, fmt.Errorf("resolve repository root symlinks %q: %w", repoRoot, err)
	}
	args := []string{"list", "-deps", "-json"}
	if len(buildTags) != 0 {
		args = append(args, "-tags", strings.Join(buildTags, ","))
	}
	args = append(args, packagePattern)

	goTool := os.Getenv("LETGO_GO")
	if goTool == "" {
		goTool, err = exec.LookPath("go")
		if err != nil {
			return nil, fmt.Errorf("resolve Go tool: %w", err)
		}
	}
	cmd := exec.Command(goTool, args...)
	cmd.Dir = root
	ignoredEnv := map[string]bool{
		"CGO_ENABLED": true, "GO111MODULE": true, "GOAMD64": true,
		"GOARCH": true, "GOENV": true, "GOEXPERIMENT": true,
		"GOFLAGS": true, "GOOS": true, "GOTOOLCHAIN": true, "GOWORK": true,
	}
	for _, entry := range os.Environ() {
		key, _, _ := strings.Cut(entry, "=")
		if !ignoredEnv[strings.ToUpper(key)] {
			cmd.Env = append(cmd.Env, entry)
		}
	}
	// A committed manifest must describe one reference graph on every host.
	// Linux/amd64 is the CI generation target; explicit values also prevent
	// ambient workspaces, GOFLAGS, experiments, and user GOENV state from
	// silently changing the selected package graph.
	cmd.Env = append(cmd.Env,
		"GOOS=linux", "GOARCH=amd64", "GOAMD64=v1", "CGO_ENABLED=1",
		"GO111MODULE=on", "GOWORK=off", "GOFLAGS=", "GOENV=off",
		"GOEXPERIMENT=", "GOTOOLCHAIN=local",
	)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("%s: %w\n%s%s", strings.Join(cmd.Args, " "), err, stdout.String(), stderr.String())
	}
	seen := make(map[string]bool)
	packageDirs := make(map[string]bool)
	modulePath := ""
	addPath := func(absolute string) error {
		rel, relErr := filepath.Rel(root, absolute)
		if relErr != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
			if relErr == nil {
				relErr = fmt.Errorf("path is outside repository root")
			}
			return fmt.Errorf("normalize generator input %q: %w", absolute, relErr)
		}
		seen[filepath.ToSlash(rel)] = true
		return nil
	}
	dec := json.NewDecoder(bytes.NewReader(stdout.Bytes()))
	for {
		var pkg goListPackage
		err := dec.Decode(&pkg)
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("decode %s output: %w\n%s%s", strings.Join(cmd.Args, " "), err, stdout.String(), stderr.String())
		}
		if pkg.Module == nil || !pkg.Module.Main {
			continue
		}
		if modulePath == "" {
			modulePath = pkg.Module.Path
		}
		packageDirs[pkg.Dir] = true
		selectedGroups := [][]string{
			pkg.GoFiles, pkg.CgoFiles, pkg.CFiles, pkg.CXXFiles, pkg.MFiles,
			pkg.HFiles, pkg.FFiles, pkg.SFiles, pkg.SwigFiles,
			pkg.SwigCXXFiles, pkg.SysoFiles,
		}
		for _, files := range selectedGroups {
			for _, file := range files {
				if err := addPath(filepath.Join(pkg.Dir, file)); err != nil {
					return nil, fmt.Errorf("%s: %w\n%s%s", strings.Join(cmd.Args, " "), err, stdout.String(), stderr.String())
				}
			}
		}
		for _, file := range pkg.EmbedFiles {
			// Broad all: patterns can see editor backups ignored by version
			// control. They are not canonical generator sources and must not
			// make the committed graph depend on local workspace debris.
			if isEphemeralBackup(file) {
				continue
			}
			if err := addPath(filepath.Join(pkg.Dir, file)); err != nil {
				return nil, fmt.Errorf("%s: %w\n%s%s", strings.Join(cmd.Args, " "), err, stdout.String(), stderr.String())
			}
		}
	}
	if modulePath == "" {
		return nil, fmt.Errorf("%s returned no packages in the main module", strings.Join(cmd.Args, " "))
	}

	// Expand from the Go-selected seed through imports in every platform/tag
	// variant, and record all package-local build sources. This deliberately
	// over-approximates the host build so Darwin/Windows/Linux generators share
	// one manifest and a newly imported local package is discovered automatically.
	queue := make([]string, 0, len(packageDirs))
	for dir := range packageDirs {
		queue = append(queue, dir)
	}
	visited := make(map[string]bool)
	buildExt := map[string]bool{
		".go": true, ".c": true, ".cc": true, ".cpp": true, ".cxx": true,
		".m": true, ".h": true, ".hh": true, ".hpp": true,
		".f": true, ".for": true, ".f90": true, ".s": true,
		".swig": true, ".swigcxx": true, ".syso": true,
	}
	for len(queue) > 0 {
		dir := queue[0]
		queue = queue[1:]
		if visited[dir] {
			continue
		}
		visited[dir] = true
		entries, readErr := os.ReadDir(dir)
		if readErr != nil {
			return nil, fmt.Errorf("read generator package directory %s: %w", dir, readErr)
		}
		for _, entry := range entries {
			if entry.IsDir() || strings.HasSuffix(entry.Name(), "_test.go") || !buildExt[strings.ToLower(filepath.Ext(entry.Name()))] {
				continue
			}
			absolute := filepath.Join(dir, entry.Name())
			if strings.HasSuffix(entry.Name(), ".go") {
				generated, genErr := isGenerated(absolute)
				if genErr != nil {
					return nil, genErr
				}
				if generated {
					rel, relErr := filepath.Rel(root, absolute)
					if relErr != nil {
						return nil, relErr
					}
					// Parse committed generated inputs selected by Go, but ignore
					// transient generated wireups absent from the canonical graph.
					if !seen[filepath.ToSlash(rel)] {
						continue
					}
				}
				parsed, parseErr := parser.ParseFile(token.NewFileSet(), absolute, nil, parser.ImportsOnly)
				if parseErr != nil {
					return nil, fmt.Errorf("parse generator dependency imports %s: %w", absolute, parseErr)
				}
				for _, imp := range parsed.Imports {
					importPath, unquoteErr := strconv.Unquote(imp.Path.Value)
					if unquoteErr != nil {
						return nil, fmt.Errorf("decode import in %s: %w", absolute, unquoteErr)
					}
					if importPath == modulePath || strings.HasPrefix(importPath, modulePath+"/") {
						relPackage := strings.TrimPrefix(strings.TrimPrefix(importPath, modulePath), "/")
						importDir := filepath.Join(root, filepath.FromSlash(relPackage))
						if !visited[importDir] {
							queue = append(queue, importDir)
						}
					}
				}
			}
			if err := addPath(absolute); err != nil {
				return nil, err
			}
		}
	}

	paths := make([]string, 0, len(seen))
	for path := range seen {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths, nil
}

// outputSpecs is the authoritative edge declaration (see the plan's table).
var outputSpecs = []outputSpec{
	{
		output:      "pkg/rt/zz_primitives_generated.go",
		inputSweeps: []sweep{{"pkg/rt", ".go"}},
		genSweeps:   []sweep{{"internal/primgen", ".go"}, {"cmd/lgprimgen", ".go"}},
	},
	{
		output:      "pkg/rt/corefns/zz_primitives_generated.go",
		inputSweeps: []sweep{{"pkg/rt/corefns", ".go"}},
		genSweeps:   []sweep{{"internal/primgen", ".go"}, {"cmd/lgprimgen", ".go"}},
	},
	{
		output:            "pkg/rt/core_compiled.lgb",
		inputSweeps:       []sweep{{"pkg/rt/core", ".lg"}},
		genPackagePattern: "./cmd/lgbgen",
		genBuildTags:      []string{"bootstrap"},
	},
	{
		output:            "pkg/rt/core_go_lowered/",
		inputSweeps:       []sweep{{"pkg/rt/core", ".lg"}},
		genPackagePattern: "./cmd/lgbgen",
		genBuildTags:      []string{"bootstrap"},
	},
	{
		output:     "pkg/ir/op_generated.go",
		inputFiles: []string{"pkg/ir/ir_ops.lg", "scripts/gen/op_generated.head"},
		genFiles:   []string{"scripts/generate.lg"},
	},
	{
		output:     "pkg/rt/ir_bridge_generated.go",
		inputFiles: []string{"pkg/ir/ir_bridge.lg", "scripts/gen/ir_bridge_generated.head"},
		genFiles:   []string{"scripts/generate.lg"},
	},
	{
		output:     "pkg/rt/core/ir/data/generated.lg",
		inputFiles: []string{"pkg/ir/ir_data.lg"},
		genFiles:   []string{"scripts/generate.lg"},
	},
}

func isDeclaredOutput(path string) bool {
	for _, spec := range outputSpecs {
		if spec.output == path {
			return true
		}
	}
	return false
}

func isInsideDeclaredDirectoryOutput(path string) bool {
	for _, spec := range outputSpecs {
		if !strings.HasSuffix(spec.output, "/") {
			continue
		}
		dir := strings.TrimSuffix(spec.output, "/")
		if path == dir || strings.HasPrefix(path, spec.output) {
			return true
		}
	}
	return false
}

// sweepFiles returns repo-relative paths under root/s.dir with extension s.ext,
// skipping directories, _test.go, and — when skipGenerated is set — generated
// files (both input and generator sweeps set it, so transient generated .go
// artifacts never enter the manifest).
func sweepFiles(repoRoot string, s sweep, skipGenerated bool) ([]string, error) {
	var out []string
	base := filepath.Join(repoRoot, s.dir)
	// Verify the sweep root exists before walking, matching the behavior of
	// explicit input files (which error on missing files).
	if _, err := os.Stat(base); err != nil {
		return nil, fmt.Errorf("sweep directory for %q missing: %s: %w", s.dir, base, err)
	}
	err := filepath.WalkDir(base, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			// WalkDir only errors on the root path after Stat succeeds if there's a
			// permissions issue; a missing file within the walk is not an error.
			return err
		}
		if d.IsDir() {
			rel, rerr := filepath.Rel(repoRoot, path)
			if rerr != nil {
				return rerr
			}
			if isInsideDeclaredDirectoryOutput(filepath.ToSlash(rel)) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, s.ext) || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		if skipGenerated && s.ext == ".go" {
			gen, gerr := isGenerated(path)
			if gerr != nil {
				return gerr
			}
			if gen {
				return nil
			}
		}
		rel, rerr := filepath.Rel(repoRoot, path)
		if rerr != nil {
			return rerr
		}
		rel = filepath.ToSlash(rel)
		out = append(out, rel)
		return nil
	})
	return out, err
}

// Edges resolves every output's sweeps/files into a sorted, deduplicated edge
// list (no hashes). Missing explicit input files are an error (a stale spec).
func Edges(repoRoot string) ([]Edge, error) {
	seen := map[Edge]bool{}
	moduleInputs := make(map[string][]string)
	var edges []Edge
	add := func(output, input, kind string) {
		e := Edge{output, input, kind}
		if !seen[e] {
			seen[e] = true
			edges = append(edges, e)
		}
	}
	for _, spec := range outputSpecs {
		for _, s := range spec.inputSweeps {
			files, err := sweepFiles(repoRoot, s, true)
			if err != nil {
				return nil, err
			}
			for _, f := range files {
				add(spec.output, f, "input")
			}
		}
		for _, f := range spec.inputFiles {
			if _, err := os.Stat(filepath.Join(repoRoot, f)); err != nil {
				return nil, fmt.Errorf("input file for %s missing: %s: %w", spec.output, f, err)
			}
			add(spec.output, f, "input")
		}
		for _, s := range spec.genSweeps {
			// Skip generated .go too: a generator dir can hold a transient,
			// gitignored generated file (e.g. cmd/lgbgen/main_gogen_ir.go from a
			// prior `-tags gogen_ir` build) that is absent in a clean CI checkout.
			// Including it would make the front-gate staleness check fail there.
			files, err := sweepFiles(repoRoot, s, true)
			if err != nil {
				return nil, err
			}
			for _, f := range files {
				add(spec.output, f, "generator")
			}
		}
		for _, f := range spec.genFiles {
			if _, err := os.Stat(filepath.Join(repoRoot, f)); err != nil && !isDeclaredOutput(f) {
				return nil, fmt.Errorf("generator file for %s missing: %s: %w", spec.output, f, err)
			}
			// A generated output can itself be a downstream generator input. Keep
			// that edge when the file is absent so readiness propagates instead of
			// turning a normal staged regeneration into a query error.
			add(spec.output, f, "generator")
		}
		if spec.genPackagePattern != "" {
			key := spec.genPackagePattern + "\x00" + strings.Join(spec.genBuildTags, "\x00")
			files, ok := moduleInputs[key]
			if !ok {
				var err error
				files, err = goModuleBuildInputs(repoRoot, spec.genPackagePattern, spec.genBuildTags...)
				if err != nil {
					return nil, fmt.Errorf("resolve generator inputs for %s: %w", spec.output, err)
				}
				moduleInputs[key] = files
			}
			for _, f := range files {
				add(spec.output, f, "generator")
			}
		}
	}
	sort.Slice(edges, func(i, j int) bool {
		if edges[i].Output != edges[j].Output {
			return edges[i].Output < edges[j].Output
		}
		if edges[i].Kind != edges[j].Kind {
			return edges[i].Kind < edges[j].Kind
		}
		return edges[i].Input < edges[j].Input
	})
	return edges, nil
}

// HashedEdge is an Edge plus the sha256 of its Input at manifest-write time.
type HashedEdge struct {
	Edge
	Sum string
}

const depManifestHeader = "# Auto-generated by `make generate`. DO NOT EDIT.\n" +
	"# query-escaped <output> <input> <kind> <sha256>   kind in {input, generator, output}\n"

func encodeManifestField(value string) string {
	return strings.ReplaceAll(url.QueryEscape(value), "%2F", "/")
}

func decodeManifestField(value string) (string, error) { return url.QueryUnescape(value) }

// WriteDepManifest resolves the edges, hashes each input and declared file
// output, and writes the query-escaped manifest deterministically. Output hashes
// are readiness records; input-only freshness checks deliberately ignore them.
func WriteDepManifest(repoRoot string) error {
	edges, err := Edges(repoRoot)
	if err != nil {
		return err
	}
	records := make([]HashedEdge, 0, len(edges)+len(outputSpecs))
	for _, e := range edges {
		sum, herr := hashFile(filepath.Join(repoRoot, e.Input))
		if herr != nil {
			return fmt.Errorf("hash %s: %w", e.Input, herr)
		}
		records = append(records, HashedEdge{Edge: e, Sum: sum})
	}
	for _, spec := range outputSpecs {
		if strings.HasSuffix(spec.output, "/") {
			continue
		}
		path := filepath.Join(repoRoot, spec.output)
		info, statErr := os.Lstat(path)
		if statErr != nil {
			return fmt.Errorf("stat generated output %s: %w", spec.output, statErr)
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("generated output %s is not a regular file", spec.output)
		}
		sum, hashErr := hashFile(path)
		if hashErr != nil {
			return fmt.Errorf("hash generated output %s: %w", spec.output, hashErr)
		}
		records = append(records, HashedEdge{
			Edge: Edge{Output: spec.output, Input: spec.output, Kind: "output"},
			Sum:  sum,
		})
	}
	sort.Slice(records, func(i, j int) bool {
		if records[i].Output != records[j].Output {
			return records[i].Output < records[j].Output
		}
		if records[i].Kind != records[j].Kind {
			return records[i].Kind < records[j].Kind
		}
		return records[i].Input < records[j].Input
	})
	var b strings.Builder
	b.WriteString(depManifestHeader)
	for _, record := range records {
		fmt.Fprintf(&b, "%s %s %s %s\n",
			encodeManifestField(record.Output), encodeManifestField(record.Input),
			encodeManifestField(record.Kind), record.Sum)
	}
	return os.WriteFile(filepath.Join(repoRoot, DepManifestRelPath), []byte(b.String()), 0644)
}

// ReadDepManifest parses the committed manifest.
func ReadDepManifest(repoRoot string) ([]HashedEdge, error) {
	f, err := os.Open(filepath.Join(repoRoot, DepManifestRelPath))
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var out []HashedEdge
	// Count occurrences rather than stopping at the first repeat: a manifest that
	// merged wrong usually carries a run of duplicated edges, and the size and
	// spread of that run is the signal for how far the merge went astray.
	seen := make(map[Edge]int)
	var dupes []Edge
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) != 4 {
			return nil, fmt.Errorf("malformed manifest line: %q", line)
		}
		fields := make([]string, 3)
		for i := range fields {
			fields[i], err = decodeManifestField(parts[i])
			if err != nil {
				return nil, fmt.Errorf("decode manifest field %q: %w", parts[i], err)
			}
		}
		edge := Edge{fields[0], fields[1], fields[2]}
		// This file has no merge driver and is one sorted record per line, so a
		// clean text merge can land both sides' record for the same edge. Every
		// downstream lookup is map-keyed and keeps whichever record came last,
		// so the conflict would resolve silently to one side. Refuse instead: no
		// digest should be taken over a manifest recording two hashes for one input.
		seen[edge]++
		if seen[edge] > 1 {
			if seen[edge] == 2 {
				dupes = append(dupes, edge)
			}
			continue
		}
		out = append(out, HashedEdge{edge, parts[3]})
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(dupes) > 0 {
		return nil, duplicateEdgeError(dupes, seen)
	}
	return out, nil
}

// duplicateEdgeError names every repeated edge, in manifest order, with its
// occurrence count.
func duplicateEdgeError(dupes []Edge, counts map[Edge]int) error {
	if len(dupes) == 1 {
		e := dupes[0]
		return fmt.Errorf("duplicate manifest entry for %s %s %s (%d occurrences)",
			e.Output, e.Input, e.Kind, counts[e])
	}
	var b strings.Builder
	fmt.Fprintf(&b, "%d duplicate manifest entries:", len(dupes))
	for _, e := range dupes {
		fmt.Fprintf(&b, "\n  %s %s %s (%d occurrences)",
			e.Output, e.Input, e.Kind, counts[e])
	}
	return errors.New(b.String())
}

func allDeclaredOutputs() []string {
	outputs := make([]string, 0, len(outputSpecs))
	for _, spec := range outputSpecs {
		outputs = append(outputs, spec.output)
	}
	sort.Strings(outputs)
	return outputs
}

// staleOutputs returns outputs whose current input/generator hashes no longer
// match the committed manifest. When checkReadiness is true, it also includes
// generated outputs that are absent or structurally incomplete.
func staleOutputs(repoRoot string, checkReadiness bool) ([]string, error) {
	recorded, err := ReadDepManifest(repoRoot)
	if err != nil {
		return nil, err
	}
	recordedOutputSums := map[string]string{}
	for _, he := range recorded {
		if he.Kind == "output" && he.Input == he.Output {
			recordedOutputSums[he.Output] = he.Sum
		}
	}
	staleSet := map[string]bool{}
	if checkReadiness {
		invalidGoOutput := false
		for _, spec := range outputSpecs {
			outPath := filepath.Join(repoRoot, spec.output)
			if strings.HasSuffix(spec.output, "/") {
				if err := CheckTreeManifest(outPath); err != nil {
					staleSet[spec.output] = true
				}
				continue
			}
			info, statErr := os.Lstat(outPath)
			if statErr != nil || !info.Mode().IsRegular() {
				staleSet[spec.output] = true
			} else {
				sum, hashErr := hashFile(outPath)
				if expected, ok := recordedOutputSums[spec.output]; hashErr != nil || !ok || sum != expected {
					staleSet[spec.output] = true
				}
			}
			if staleSet[spec.output] && filepath.Ext(spec.output) == ".go" {
				invalidGoOutput = true
			}
		}
		if invalidGoOutput {
			// Generator dependency discovery uses `go list`. Any changed declared
			// Go output can make that query fail despite valid Go syntax (for
			// example through a bad import/embed directive). Conservatively
			// regenerate all outputs before dependency discovery in this
			// exceptional recovery path.
			return allDeclaredOutputs(), nil
		}
	}
	recByOutput := map[string]map[string]string{} // output -> input -> sum
	for _, he := range recorded {
		if he.Kind == "output" {
			continue
		}
		if recByOutput[he.Output] == nil {
			recByOutput[he.Output] = map[string]string{}
		}
		recByOutput[he.Output][he.Input] = he.Sum
	}
	current, err := Edges(repoRoot)
	if err != nil {
		return nil, err
	}
	for _, e := range current {
		rec, ok := recByOutput[e.Output][e.Input]
		if !ok {
			staleSet[e.Output] = true
			continue
		}
		sum, herr := hashFile(filepath.Join(repoRoot, e.Input))
		if herr != nil {
			if os.IsNotExist(herr) && isDeclaredOutput(e.Input) {
				staleSet[e.Output] = true
				continue
			}
			return nil, herr
		}
		if sum != rec {
			staleSet[e.Output] = true
		}
	}
	// An input removed since the manifest was written also dirties the output.
	curByOutput := map[string]map[string]bool{}
	for _, e := range current {
		if curByOutput[e.Output] == nil {
			curByOutput[e.Output] = map[string]bool{}
		}
		curByOutput[e.Output][e.Input] = true
	}
	for _, he := range recorded {
		if he.Kind == "output" {
			continue
		}
		if !curByOutput[he.Output][he.Input] {
			staleSet[he.Output] = true
		}
	}
	var out []string
	for o := range staleSet {
		out = append(out, o)
	}
	sort.Strings(out)
	return out, nil
}

// StaleOutputs returns outputs that need regeneration because either their
// recorded input hashes changed or their generated files are not ready.
func StaleOutputs(repoRoot string) ([]string, error) {
	return staleOutputs(repoRoot, true)
}

// StaleInputOutputs returns outputs whose recorded input hashes are stale,
// without consulting generated-output state. It is safe to run before a clean
// checkout has restored gitignored outputs.
func StaleInputOutputs(repoRoot string) ([]string, error) {
	return staleOutputs(repoRoot, false)
}

// CheckDepManifest returns nil when the manifest matches the current sources,
// else an error naming the first stale output and a changed input.
func CheckDepManifest(repoRoot string) error {
	stale, err := StaleInputOutputs(repoRoot)
	if err != nil {
		return err
	}
	if len(stale) == 0 {
		return nil
	}
	return fmt.Errorf("dependency manifest stale for %d output(s): %s\n%s",
		len(stale), strings.Join(stale, ", "), Remediation)
}
