package test

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// scripts/lint.lg flags comments that narrate the change rather than describe
// the code. Its skip markers are the part most likely to rot silently: a marker
// that can never match costs nothing at runtime and shows up only as a stray
// finding, which is how "//go:" survived review (nooga/let-go#836). The fixture
// below pins one line per marker plus the matching rules the phrase list leans
// on, so a change to the stripping or normalization has to move a line number.

// lintFixtureGo pairs each comment with the line it lands on; want-hit lines are
// listed in lintWantGo. Keep the two in sync when editing.
const lintFixtureGo = `package fixture

//go:generate run this pr adds a flag
func A() {}

// Code generated by tool. this pr adds a flag
func B() {}

//lgbgen: this pr adds a flag
func C() {}

// lint:ignore — quoting "this pr" is what the escape hatch is for
func D() {}

// Copyright 2026 — this pr adds a flag
func E() {}

// this pr adds a flag
func F() {}

// this process adds a flag
func G() {}

// the arms are not what they
// used to be before the split
func H() {}
`

// Line 18 is the plain devlog comment; 24 is the block that wraps a phrase
// across two lines and reports at the line it starts on.
var lintWantGo = []int{18, 24}

const lintFixtureLg = `;; this commit renames the arms
(def a 1)

;; lint:ignore — this commit is quoted on purpose
(def b 2)

;; the split is done; this is the current shape
(def c 3)
`

var lintWantLg = []int{1}

func TestLintLgSkipMarkersAndPhraseMatching(t *testing.T) {
	dir := t.TempDir()
	goFixture := filepath.Join(dir, "fixture.go")
	lgFixture := filepath.Join(dir, "fixture.lg")
	if err := os.WriteFile(goFixture, []byte(lintFixtureGo), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(lgFixture, []byte(lintFixtureLg), 0644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir)
	cmd.Dir = repoRoot
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg: %v\n%s", err, out)
	}

	got := map[string][]int{}
	for _, line := range strings.Split(string(out), "\n") {
		if !strings.Contains(line, "[devlog-comment]") {
			continue
		}
		loc := strings.Fields(line)[0]
		i := strings.LastIndex(loc, ":")
		n, convErr := strconv.Atoi(loc[i+1:])
		if convErr != nil {
			t.Fatalf("unparsable finding location %q in:\n%s", loc, out)
		}
		got[filepath.Base(loc[:i])] = append(got[filepath.Base(loc[:i])], n)
	}

	for file, want := range map[string][]int{"fixture.go": lintWantGo, "fixture.lg": lintWantLg} {
		if !equalInts(got[file], want) {
			t.Errorf("%s: findings at lines %v, want %v\n%s", file, got[file], want, out)
		}
	}
}

// R1 — commented-out code (`.lg` only; Go is explicitly deferred, see
// scripts/lint.lg's own R1 section comment). A comment whose body reads as a
// balanced, delimited form is flagged; a bare identifier/literal and ordinary
// prose (even prose that happens to contain a parenthetical aside without a
// full balanced code shape) are not.
const lintFixtureR1 = `;; (inc counter)
(def a 1)

;; n
(def b 2)

;; increment the counter for retries
(def c 3)

;; 42
(def d 4)
`

var lintWantR1 = []int{1}

func TestLintR1CommentedOutCode(t *testing.T) {
	dir := t.TempDir()
	lgFixture := filepath.Join(dir, "fixture.lg")
	if err := os.WriteFile(lgFixture, []byte(lintFixtureR1), 0644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir)
	cmd.Dir = repoRoot
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg: %v\n%s", err, out)
	}

	got := []int{}
	for _, line := range strings.Split(string(out), "\n") {
		if !strings.Contains(line, "[commented-out-code]") {
			continue
		}
		loc := strings.Fields(line)[0]
		// loc is "path:line-end"
		loc = strings.SplitN(loc, ":", 2)[1]
		loc = strings.SplitN(loc, "-", 2)[0]
		n, convErr := strconv.Atoi(loc)
		if convErr != nil {
			t.Fatalf("unparsable finding location %q in:\n%s", loc, out)
		}
		got = append(got, n)
	}

	if !equalInts(got, lintWantR1) {
		t.Errorf("commented-out-code findings at lines %v, want %v\n%s", got, lintWantR1, out)
	}

	// Go source must never be flagged for R1: the rule is deferred there.
	goFixture := filepath.Join(dir, "other.go")
	goSrc := "package fixture\n\n// x := computeSomething(a, b)\nfunc F() {}\n"
	if err := os.WriteFile(goFixture, []byte(goSrc), 0644); err != nil {
		t.Fatal(err)
	}
	out2, err := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir).CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg: %v\n%s", err, out2)
	}
	for _, line := range strings.Split(string(out2), "\n") {
		if strings.Contains(line, "[commented-out-code]") && strings.Contains(line, "other.go") {
			t.Errorf("R1 must not fire on Go source (deferred): %s", line)
		}
	}
}

// R2 — restatement: the comment's content words overlap heavily with the
// identifiers of the form immediately following it, and it adds nothing that
// isn't already spelled out by that form. A comment giving a reason, even one
// naming the same identifiers, is not flagged because it also carries extra
// content words.
const lintFixtureR2 = `;; set counter
(set counter val)

;; set counter because writer holds the exclusive lock
(set counter val)
`

func TestLintR2Restatement(t *testing.T) {
	dir := t.TempDir()
	lgFixture := filepath.Join(dir, "fixture.lg")
	if err := os.WriteFile(lgFixture, []byte(lintFixtureR2), 0644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir)
	cmd.Dir = repoRoot
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg: %v\n%s", err, out)
	}

	got := []int{}
	for _, line := range strings.Split(string(out), "\n") {
		if !strings.Contains(line, "[restatement]") {
			continue
		}
		loc := strings.Fields(line)[0]
		loc = strings.SplitN(loc, ":", 2)[1]
		loc = strings.SplitN(loc, "-", 2)[0]
		n, convErr := strconv.Atoi(loc)
		if convErr != nil {
			t.Fatalf("unparsable finding location %q in:\n%s", loc, out)
		}
		got = append(got, n)
	}

	want := []int{1}
	if !equalInts(got, want) {
		t.Errorf("restatement findings at lines %v, want %v\n%s", got, want, out)
	}
}

// R3 — duplicated comment: the same normalized comment text appears in three
// or more places across the corpus. Twice is not enough; a licence header
// (already a skip-marker) is never counted even if repeated many times.
func TestLintR3DuplicatedComment(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"a.lg": ";; Copyright 2026 Example — do not remove\n\n;; retries three times before giving up\n(def a 1)\n",
		"b.lg": ";; Copyright 2026 Example — do not remove\n\n;; retries three times before giving up\n(def b 2)\n",
		"c.lg": ";; Copyright 2026 Example — do not remove\n\n;; retries three times before giving up\n(def c 3)\n",
		"d.lg": ";; Copyright 2026 Example — do not remove\n\n;; seen only twice, should not flag\n(def d 4)\n",
		"e.lg": ";; Copyright 2026 Example — do not remove\n\n;; seen only twice, should not flag\n(def e 5)\n",
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
	}

	out, err := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir).CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg: %v\n%s", err, out)
	}

	dupCount, copyrightHit, twiceHit := 0, false, false
	for _, line := range strings.Split(string(out), "\n") {
		if !strings.Contains(line, "[duplicated-comment]") {
			continue
		}
		dupCount++
		if strings.Contains(line, "copyright") || strings.Contains(strings.ToLower(line), "do not remove") {
			copyrightHit = true
		}
		if strings.Contains(line, "seen only twice") {
			twiceHit = true
		}
	}

	if dupCount != 3 {
		t.Errorf("duplicated-comment findings = %d, want 3 (one per occurrence of the 3x comment)\n%s", dupCount, out)
	}
	if copyrightHit {
		t.Errorf("licence header must never be flagged as duplicated:\n%s", out)
	}
	if twiceHit {
		t.Errorf("a comment seen only twice must not flag:\n%s", out)
	}
}

// R4 — comment density outlier: per definition, comment-lines/total-lines,
// flagged when it exceeds the 95th percentile computed over the corpus
// itself. This fixture builds 20 definitions with a strictly increasing,
// hand-computable ratio (Ci comment lines over a fixed 2-line body, Ci from
// 3 to 22 so every definition, including the smallest, clears the R4
// min-definition-lines guard), so the percentile is known: with
// nearest-rank on 20 values, rank = ceil(0.95*20) = 19, i.e. the 19th
// smallest (Ci=21, ratio 21/23=0.9130). Only the strict maximum (Ci=22,
// ratio 22/24=0.9167) beats that threshold, so exactly one definition must
// be flagged: the last one.
func buildLintFixtureR4() (string, int) {
	var b strings.Builder
	lastCommentStart := 0
	line := 1
	for ci := 3; ci <= 22; ci++ {
		if ci > 3 {
			b.WriteString("\n")
			line++
		}
		lastCommentStart = line
		for c := 1; c <= ci; c++ {
			fmt.Fprintf(&b, ";; c%d-%d\n", ci, c)
			line++
		}
		fmt.Fprintf(&b, "(defn f%d [x]\n  x)\n", ci)
		line += 2
	}
	return b.String(), lastCommentStart
}

func TestLintR4DensityOutlier(t *testing.T) {
	dir := t.TempDir()
	src, lastCommentStart := buildLintFixtureR4()
	lgFixture := filepath.Join(dir, "fixture.lg")
	if err := os.WriteFile(lgFixture, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	out, err := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir).CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg: %v\n%s", err, out)
	}

	got := []int{}
	for _, l := range strings.Split(string(out), "\n") {
		if !strings.Contains(l, "[comment-density-outlier]") {
			continue
		}
		loc := strings.Fields(l)[0]
		loc = strings.SplitN(loc, ":", 2)[1]
		loc = strings.SplitN(loc, "-", 2)[0]
		n, convErr := strconv.Atoi(loc)
		if convErr != nil {
			t.Fatalf("unparsable finding location %q in:\n%s", loc, out)
		}
		got = append(got, n)
	}

	want := []int{lastCommentStart}
	if !equalInts(got, want) {
		t.Errorf("comment-density-outlier findings at lines %v, want %v (the Ci=21 definition)\n%s", got, want, out)
	}
}

// --edn / --gate: machine-readable output and opt-in exit codes.
func TestLintEdnAndGate(t *testing.T) {
	dir := t.TempDir()
	// One R1 (commented-out code) finding and nothing else interesting.
	src := ";; (inc counter)\n(def a 1)\n"
	if err := os.WriteFile(filepath.Join(dir, "fixture.lg"), []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	// --edn: stdout must be exactly one EDN vector of finding maps.
	ednOut, err := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), "--edn", dir).CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg --edn: %v\n%s", err, ednOut)
	}
	trimmed := strings.TrimSpace(string(ednOut))
	if !strings.HasPrefix(trimmed, "[") || !strings.HasSuffix(trimmed, "]") {
		t.Fatalf("--edn output is not a single EDN vector:\n%s", trimmed)
	}
	if !strings.Contains(trimmed, ":commented-out-code") {
		t.Errorf("--edn output missing the R1 finding:\n%s", trimmed)
	}
	if !strings.Contains(trimmed, ":line") || !strings.Contains(trimmed, ":end") {
		t.Errorf("--edn findings must carry :line and :end:\n%s", trimmed)
	}

	// --gate on a kind with findings exits non-zero.
	gateCmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"),
		"--gate", "commented-out-code", dir)
	gateOut, gateErr := gateCmd.CombinedOutput()
	if gateErr == nil {
		t.Fatalf("--gate commented-out-code should exit non-zero when R1 has findings:\n%s", gateOut)
	}

	// --gate on a kind with no findings exits zero.
	cleanCmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"),
		"--gate", "duplicated-comment", dir)
	cleanOut, cleanErr := cleanCmd.CombinedOutput()
	if cleanErr != nil {
		t.Fatalf("--gate duplicated-comment should exit zero (no such findings): %v\n%s", cleanErr, cleanOut)
	}

	// Default mode (no --gate) still exits zero even though R1 has findings.
	defaultCmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir)
	defaultOut, defaultErr := defaultCmd.CombinedOutput()
	if defaultErr != nil {
		t.Fatalf("default mode must exit zero regardless of findings: %v\n%s", defaultErr, defaultOut)
	}

	// Gating on the R5 heuristic kind must never fail the run, even though
	// it is not a real gate target.
	r5GateCmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"),
		"--gate", "devlog-comment", dir)
	r5Out, r5Err := r5GateCmd.CombinedOutput()
	if r5Err != nil {
		t.Fatalf("--gate devlog-comment must not gate (R5 is heuristic-only): %v\n%s", r5Err, r5Out)
	}
}

func equalInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
