package test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// scripts/lint.lg flags comments that narrate the change rather than describe
// the code. Its skip markers are the part most likely to rot silently: a marker
// that can never match costs nothing at runtime and shows up only as a stray
// finding, which is how "//go:" survived review (nooga/let-go#836). The fixture
// below pins one line per marker plus the matching rules the phrase list leans
// on, so a change to the stripping or normalization has to move a line number.

// lintFixtureGo pairs each comment with the line it lands on; want-hit lines are
// listed in lintWantGo. Keep the two in sync when editing.
const lintFixtureGo = `package fixture

//go:generate run this pr adds a flag
func A() {}

// Code generated by tool. this pr adds a flag
func B() {}

//lgbgen: this pr adds a flag
func C() {}

// lint:ignore — quoting "this pr" is what the escape hatch is for
func D() {}

// Copyright 2026 — this pr adds a flag
func E() {}

// this pr adds a flag
func F() {}

// this process adds a flag
func G() {}

// the arms are not what they
// used to be before the split
func H() {}
`

// Line 18 is the plain devlog comment; 24 is the block that wraps a phrase
// across two lines and reports at the line it starts on.
var lintWantGo = []int{18, 24}

const lintFixtureLg = `;; this commit renames the arms
(def a 1)

;; lint:ignore — this commit is quoted on purpose
(def b 2)

;; the split is done; this is the current shape
(def c 3)
`

var lintWantLg = []int{1}

func TestLintLgSkipMarkersAndPhraseMatching(t *testing.T) {
	dir := t.TempDir()
	goFixture := filepath.Join(dir, "fixture.go")
	lgFixture := filepath.Join(dir, "fixture.lg")
	if err := os.WriteFile(goFixture, []byte(lintFixtureGo), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(lgFixture, []byte(lintFixtureLg), 0644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(lgBin, filepath.Join(repoRoot, "scripts", "lint.lg"), dir)
	cmd.Dir = repoRoot
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("lint.lg: %v\n%s", err, out)
	}

	got := map[string][]int{}
	for _, line := range strings.Split(string(out), "\n") {
		if !strings.Contains(line, "[devlog-comment]") {
			continue
		}
		loc := strings.Fields(line)[0]
		i := strings.LastIndex(loc, ":")
		n, convErr := strconv.Atoi(loc[i+1:])
		if convErr != nil {
			t.Fatalf("unparsable finding location %q in:\n%s", loc, out)
		}
		got[filepath.Base(loc[:i])] = append(got[filepath.Base(loc[:i])], n)
	}

	for file, want := range map[string][]int{"fixture.go": lintWantGo, "fixture.lg": lintWantLg} {
		if !equalInts(got[file], want) {
			t.Errorf("%s: findings at lines %v, want %v\n%s", file, got[file], want, out)
		}
	}
}

func equalInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
