version: 2

project_name: let-go

before:
  hooks:
    - go mod tidy
    - go test -timeout 60s ./...

builds:
  - main: .
    binary: lg
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - repository:
      owner: nooga
      name: let-go
      folder: HomebrewFormula
    homepage: https://github.com/nooga/let-go
    description: A Clojure dialect implemented as a bytecode VM in Go
    license: MIT
    install: |
      bin.install "lg"
    test: |
      system bin/"lg", "-e", "(+ 1 1)"
