# This file was generated by GoReleaser. DO NOT EDIT.
cask "let-go" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "e10fc924ee8a618183a98711cba6d6031d6932ad626145717ec6150fa3e589a6"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b55c5ce09fdc81fa7a653d0be1eb6a686872c5e06aedc5f5401160db815e4acd"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2be84d28886c272dbe62db6436c03b35eb1dab79d3f989de715822f5a26c7a03"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fab63698476e210495c93941123b7f4cfe796e79aa6b7738db1856fde221f91e"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "let-go"
  desc "Clojure dialect implemented as a bytecode VM in Go"
  homepage "https://github.com/nooga/let-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lg"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lg"] if OS.mac?
  end

  # No zap stanza required

end
