# This file was generated by GoReleaser. DO NOT EDIT.
cask "let-go" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "0836582b45814611e7a1c1bfc6b06aabfa4b7c6a7b6028c02f8926a361998a7d"
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be0a3c8cdc64225e581cb37807f241daebef480101f771d938aa4a1ca734f8f2"
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d23d8b599c63f8c1f16a2d5150519034065c04859f4da3121748c95749e6c20"
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "57a80c1f5e57e308b4e95200c3b8e60a0322824ad8871fe2a23e1d44f8cee77d"
      url "https://github.com/nooga/let-go/releases/download/v2.0.2/let-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "let-go"
  desc "Clojure dialect implemented as a bytecode VM in Go"
  homepage "https://github.com/nooga/let-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lg"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lg"] if OS.mac?
  end

  # No zap stanza required
end
