# This file was generated by GoReleaser. DO NOT EDIT.
cask "let-go" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "95ba54373ab0e3d207c1bf0035c079405754e113a21eb3ba100e4414814608b6"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb869ab744ac580fbcc115d8d13b33c0e11f647071b97729f8faedcfb275cc76"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57b25c21ee7f4683eb69d127bf7524be35a5cea073f4f98d9bb3bad786d0fc0b"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b5af6c93980760866857f0bce0c865c7883b5b9ee40573ab19ed02f9801cfbf8"
      url "https://github.com/nooga/let-go/releases/download/v#{version}/let-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "let-go"
  desc "Clojure dialect implemented as a bytecode VM in Go"
  homepage "https://github.com/nooga/let-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lg"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lg"] if OS.mac?
  end

  # No zap stanza required

end
