/*
 * Copyright (c) 2026 let-go contributors; see CONTRIBUTORS.
 * SPDX-License-Identifier: MIT
 */

package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/nooga/let-go/pkg/gomod"
)

// A caller-supplied module lets -w and `lg compile` build inside a Go
// module whose go.mod the caller controls, so it can require packages beyond
// let-go. let-go owns one directory inside it and never edits go.mod or go.sum.

// generatedDirName is the directory let-go owns inside a caller-supplied
// module. The generated main package and any lowered packages live here, so
// their import path is the module path plus this name.
const generatedDirName = "lgprogram"

// generatedMarker marks generatedDirName as let-go's. A directory without it
// is never written into, so an existing package of the same name — a
// hand-written launcher, say — is refused rather than replaced.
const generatedMarker = ".lg-generated"

const generatedMarkerText = "This directory is generated by lg and replaced on every build.\n"

// callerModule is a Go module the caller prepared for a build.
type callerModule struct {
	Root string // directory holding go.mod
	Path string // module path declared in go.mod
}

func (m callerModule) GenDir() string { return filepath.Join(m.Root, generatedDirName) }

// ImportPath is GenDir's import path, the prefix lowered packages import
// each other under.
func (m callerModule) ImportPath() string { return m.Path + "/" + generatedDirName }

// loadCallerModule reads the module at dir, which must hold go.mod itself.
// The module path comes from `go mod edit -json`, which parses go.mod the way
// the toolchain that builds it will, without touching the network or the file.
func loadCallerModule(dir string) (callerModule, error) {
	root, err := filepath.Abs(dir)
	if err != nil {
		return callerModule{}, err
	}
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		return callerModule{}, fmt.Errorf("module %s: no go.mod: %w", dir, err)
	}
	cmd := exec.Command(gomod.GoToolPath(), "mod", "edit", "-json")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return callerModule{}, fmt.Errorf("module %s: reading go.mod: %s", dir, ee.Stderr)
		}
		return callerModule{}, fmt.Errorf("module %s: reading go.mod: %w", dir, err)
	}
	var mod struct{ Module struct{ Path string } }
	if err := json.Unmarshal(out, &mod); err != nil {
		return callerModule{}, fmt.Errorf("module %s: reading go.mod: %w", dir, err)
	}
	if mod.Module.Path == "" {
		return callerModule{}, fmt.Errorf("module %s: go.mod declares no module path", dir)
	}
	return callerModule{Root: root, Path: mod.Module.Path}, nil
}

// prepareGenDir empties GenDir for a fresh build and marks it as let-go's.
// A missing directory is created; one that exists without the marker is
// refused, empty or not, because let-go cannot tell whether it is someone's.
func (m callerModule) prepareGenDir() error {
	dir := m.GenDir()
	if _, err := os.Stat(dir); err == nil {
		if _, err := os.Stat(filepath.Join(dir, generatedMarker)); err != nil {
			return fmt.Errorf("refusing to write into %s: it exists and has no %s marker, so lg did not create it", dir, generatedMarker)
		}
		if err := os.RemoveAll(dir); err != nil {
			return err
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.Mkdir(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, generatedMarker), []byte(generatedMarkerText), 0644)
}

// importsFileName holds the blank imports that -import adds to the generated
// main package.
const importsFileName = "imports.go"

// writeImports blank-imports each package into the generated main package, so
// a package that registers namespaces from init() is linked in and its init
// runs. A path that names no package in the module's requirements fails at go
// build, which reports it there; go.mod is never edited to add one.
func (m callerModule) writeImports(imports []string) error {
	if len(imports) == 0 {
		return nil
	}
	paths := slices.Sorted(slices.Values(imports))
	paths = slices.Compact(paths)
	var b strings.Builder
	b.WriteString("// Code generated by lg from -import flags. DO NOT EDIT.\n\npackage main\n\nimport (\n")
	for _, p := range paths {
		if strings.TrimSpace(p) == "" {
			return fmt.Errorf("-import: empty package path")
		}
		b.WriteString("\t_ " + strconv.Quote(p) + "\n")
	}
	b.WriteString(")\n")
	return os.WriteFile(filepath.Join(m.GenDir(), importsFileName), []byte(b.String()), 0644)
}

// openCallerModule is the step -w and `lg compile` share when given a module:
// it prepares the generated directory and blank-imports the -import packages.
func openCallerModule(dir string, imports []string) (callerModule, error) {
	m, err := loadCallerModule(dir)
	if err != nil {
		return callerModule{}, err
	}
	if err := m.prepareGenDir(); err != nil {
		return callerModule{}, err
	}
	return m, m.writeImports(imports)
}
