/*
 * Copyright (c) 2026 Norman Nunley, Jr <nnunley@gmail.com>
 * Part of the let-go project; see CONTRIBUTORS for full list of authors.
 * SPDX-License-Identifier: MIT
 */

// Code generated by pkg/ir/ir_ops.lg. DO NOT EDIT.
//
// Package ir — indexed-RPN, block-parameter SSA IR for let-go.
//
// Design references:
//   - Burak Emir, "Indexed Reverse Polish Notation" (burakemir.ch)
//   - Carbon Language semantic IR (toolchain/sem_ir)
//   - Swift SIL, Cranelift, MLIR — all use block-parameter SSA
//
// Op kinds are catalogued in pkg/ir/ir_ops.lg. Each op
// declares its operand arity (number of input values popped from the
// RPN-walk stack), the number of values it pushes (0 or 1), and a
// "pure" flag controlling whether optimization passes may CSE / fold
// / hoist it.

package ir

import "github.com/nooga/let-go/pkg/vm"

// Op is the kind of an IR node.
type Op uint16

const (
	OpInvalid    Op = iota
	OpConst         // .Aux = vm.Value (the constant; lowered as OP_LOAD_CONST with interned index)
	OpLoadArg       // .Aux = int (arg index)
	OpLoadVar       // .Aux = *vm.Var; var roots are mutable
	OpLoadClosed    // .Aux = int (closed-over index)
	OpBlockArg      // block parameter
	OpSetVar        // .Refs[0] = var (Const aux=*vm.Var), .Refs[1] = value; pushes var back
	OpCall          // .Refs[0] = fn, .Refs[1:] = args; .Aux = arity int
	OpTailCall      // tail call ends a block
	OpAdd
	OpSub
	OpMul
	OpQuot // clojure.core/quot — integer quotient truncated toward zero. int/int lowers to native Go `/` (which truncates identically); any float/ratio/boxed operand lowers via rt.QuotValue (native float `/` does NOT truncate)
	OpDiv  // clojure.core// — true division. float/float lowers to native Go `/`; any other operand mix (int/int -> Ratio, mixed -> Float) lowers via rt.DivValue. Distinguished from Quot by op-kw in lower-go (both render Go `/`)
	OpLt
	OpLte
	OpGt
	OpGte
	OpEq
	OpInc
	OpDec
	OpPop         // discard top stack value; no result (OP_POP)
	OpReturn      // .Refs[0] = value
	OpBranch      // unconditional; .Aux = *BranchTarget
	OpBranchIf    // .Refs[0] = cond; .Aux = struct{True,False *BranchTarget}
	OpMakeClosure // .Refs[0] = *Func value (the func to wrap as a closure)
	OpPushClosed  // .Refs[0] = closure, .Refs[1] = value to attach
	OpTry         // .Refs[0] = body closure; then optional handler closure (binds the caught value), then optional finally closure; .Aux = {:has-handler bool :has-finally bool}
	OpDot         // .Refs[0] = obj; .Aux = field symbol; Go struct field selector obj.field (gogen_ir path only)
	OpDef         // .Refs[0] = var (Const aux=*vm.Var), optional .Refs[1] = value; interns + returns the var (2-ref also sets root)
)

// opInfo describes an Op's structural metadata.
type opInfo struct {
	name       string
	stackIn    int  // -1 = variable (decoded from Aux/arity)
	stackOut   int  // 0 or 1
	pure       bool // safe to CSE, fold, hoist
	terminator bool // ends a basic block
}

var opTable = [...]opInfo{
	OpInvalid:     {"INVALID", 0, 0, false, false},
	OpConst:       {"Const", 0, 1, true, false},
	OpLoadArg:     {"LoadArg", 0, 1, true, false},
	OpLoadVar:     {"LoadVar", 0, 1, false, false},
	OpLoadClosed:  {"LoadClosed", 0, 1, true, false},
	OpBlockArg:    {"BlockArg", 0, 1, true, false},
	OpSetVar:      {"SetVar", 2, 1, false, false},
	OpCall:        {"Call", -1, 1, false, false},
	OpTailCall:    {"TailCall", -1, 1, false, true},
	OpAdd:         {"Add", 2, 1, true, false},
	OpSub:         {"Sub", 2, 1, true, false},
	OpMul:         {"Mul", 2, 1, true, false},
	OpQuot:        {"Quot", 2, 1, true, false},
	OpDiv:         {"Div", 2, 1, true, false},
	OpLt:          {"Lt", 2, 1, true, false},
	OpLte:         {"Lte", 2, 1, true, false},
	OpGt:          {"Gt", 2, 1, true, false},
	OpGte:         {"Gte", 2, 1, true, false},
	OpEq:          {"Eq", 2, 1, true, false},
	OpInc:         {"Inc", 1, 1, true, false},
	OpDec:         {"Dec", 1, 1, true, false},
	OpPop:         {"Pop", 1, 0, false, false},
	OpReturn:      {"Return", 1, 0, false, true},
	OpBranch:      {"Branch", 0, 0, false, true},
	OpBranchIf:    {"BranchIf", 1, 0, false, true},
	OpMakeClosure: {"MakeClosure", 1, 1, false, false},
	OpPushClosed:  {"PushClosed", 2, 1, false, false},
	OpTry:         {"Try", -1, 1, false, false},
	OpDot:         {"Dot", 1, 1, false, false},
	OpDef:         {"Def", -1, 1, false, false},
}

// String returns the op's display name (or "Op?" for an unknown op).
func (op Op) String() string {
	if int(op) < len(opTable) {
		return opTable[op].name
	}
	return "Op?"
}

// IsTerminator reports whether op ends a basic block.
func (op Op) IsTerminator() bool {
	if int(op) < len(opTable) {
		return opTable[op].terminator
	}
	return false
}

// IsPure reports whether op has no observable side effects.
func (op Op) IsPure() bool {
	if int(op) < len(opTable) {
		return opTable[op].pure
	}
	return false
}

// StackOut returns the number of values op pushes (0 or 1).
func (op Op) StackOut() int {
	if int(op) < len(opTable) {
		return opTable[op].stackOut
	}
	return 0
}

func isCheapMaterializeOp(op Op) bool {
	switch op {
	case OpConst, OpLoadArg, OpLoadVar, OpLoadClosed:
		return true
	default:
		return false
	}
}

func irOpToBytecode(op Op) int32 {
	switch op {
	case OpConst:
		return vm.OP_LOAD_CONST
	case OpLoadArg:
		return vm.OP_LOAD_ARG
	case OpLoadVar:
		return vm.OP_LOAD_VAR
	case OpLoadClosed:
		return vm.OP_LOAD_CLOSEDOVER
	case OpSetVar:
		return vm.OP_SET_VAR
	case OpCall:
		return vm.OP_INVOKE
	case OpTailCall:
		return vm.OP_TAIL_CALL
	case OpAdd:
		return vm.OP_ADD
	case OpSub:
		return vm.OP_SUB
	case OpMul:
		return vm.OP_MUL
	case OpQuot:
		return vm.OP_QUOT
	case OpDiv:
		return vm.OP_DIV
	case OpLt:
		return vm.OP_LT
	case OpLte:
		return vm.OP_LTE
	case OpGt:
		return vm.OP_GT
	case OpGte:
		return vm.OP_GTE
	case OpEq:
		return vm.OP_EQ
	case OpInc:
		return vm.OP_INC
	case OpDec:
		return vm.OP_DEC
	case OpReturn:
		return vm.OP_RETURN
	case OpBranch:
		return vm.OP_JUMP
	case OpBranchIf:
		return vm.OP_BRANCH_FALSE
	case OpMakeClosure:
		return vm.OP_MAKE_CLOSURE
	case OpPushClosed:
		return vm.OP_PUSH_CLOSEDOVER
	default:
		return vm.OP_NOOP
	}
}

func bytecodeToIROp(op int32) Op {
	switch op & 255 {
	case vm.OP_LOAD_CONST:
		return OpConst
	case vm.OP_LOAD_ARG:
		return OpLoadArg
	case vm.OP_LOAD_VAR:
		return OpLoadVar
	case vm.OP_LOAD_CLOSEDOVER:
		return OpLoadClosed
	case vm.OP_SET_VAR:
		return OpSetVar
	case vm.OP_INVOKE:
		return OpCall
	case vm.OP_TAIL_CALL:
		return OpTailCall
	case vm.OP_ADD:
		return OpAdd
	case vm.OP_SUB:
		return OpSub
	case vm.OP_MUL:
		return OpMul
	case vm.OP_QUOT:
		return OpQuot
	case vm.OP_DIV:
		return OpDiv
	case vm.OP_LT:
		return OpLt
	case vm.OP_LTE:
		return OpLte
	case vm.OP_GT:
		return OpGt
	case vm.OP_GTE:
		return OpGte
	case vm.OP_EQ:
		return OpEq
	case vm.OP_INC:
		return OpInc
	case vm.OP_DEC:
		return OpDec
	case vm.OP_RETURN:
		return OpReturn
	case vm.OP_JUMP:
		return OpBranch
	case vm.OP_BRANCH_FALSE:
		return OpBranchIf
	case vm.OP_MAKE_CLOSURE:
		return OpMakeClosure
	case vm.OP_PUSH_CLOSEDOVER:
		return OpPushClosed
	default:
		return OpInvalid
	}
}
