/*
 * Copyright (c) 2026 Norman Nunley, Jr <nnunley@gmail.com>
 * Part of the let-go project; see CONTRIBUTORS for full list of authors.
 * SPDX-License-Identifier: MIT
 */

// Code generated by pkg/ir/ir_ops.lg. DO NOT EDIT.
//
// Package ir — indexed-RPN, block-parameter SSA IR for let-go.
//
// Design references:
//   - Burak Emir, "Indexed Reverse Polish Notation" (burakemir.ch)
//   - Carbon Language semantic IR (toolchain/sem_ir)
//   - Swift SIL, Cranelift, MLIR — all use block-parameter SSA
//
// Op kinds are catalogued in pkg/ir/ir_ops.lg. Each op
// declares its operand arity (number of input values popped from the
// RPN-walk stack), the number of values it pushes (0 or 1), and a
// "pure" flag controlling whether optimization passes may CSE / fold
// / hoist it.

package ir

import "github.com/nooga/let-go/pkg/vm"

// Op is the kind of an IR node.
type Op uint16

const (
	OpInvalid    Op = iota
	OpConst         // .Aux = vm.Value (the constant; lowered as OP_LOAD_CONST with interned index)
	OpLoadArg       // .Aux = int (arg index)
	OpLoadVar       // .Aux = *vm.Var; var roots are mutable
	OpLoadClosed    // .Aux = int (closed-over index)
	OpBlockArg      // block parameter
	OpSetVar        // .Refs[0] = var (Const aux=*vm.Var), .Refs[1] = value; pushes var back
	OpCall          // .Refs[0] = fn, .Refs[1:] = args; .Aux = arity int. infer? stays false: the :call arm (call-dtype/call-core-type) is typeinfer-coupled, not yet reified
	OpTailCall      // tail call ends a block. NOT in typeinfer's terminator-ops set (infers :unknown via default), so infer? is false
	OpAdd
	OpSub
	OpMul
	OpBitAnd                // clojure.core/bit-and — integer bitwise and
	OpBitOr                 // clojure.core/bit-or — integer bitwise or
	OpBitXor                // clojure.core/bit-xor — integer bitwise xor
	OpBitAndNot             // clojure.core/bit-and-not — integer bit clear (&^)
	OpBitShiftLeft          // clojure.core/bit-shift-left — integer left shift
	OpBitShiftRight         // clojure.core/bit-shift-right — integer arithmetic right shift
	OpUnsignedBitShiftRight // clojure.core/unsigned-bit-shift-right — integer logical right shift
	OpQuot                  // clojure.core/quot — integer quotient truncated toward zero. int/int lowers to native Go `/` (which truncates identically); any float/ratio/boxed operand lowers via rt.QuotValue (native float `/` does NOT truncate)
	OpDiv                   // clojure.core// — true division. float/float lowers to native Go `/`; any other operand mix (int/int -> Ratio, mixed -> Float) lowers via rt.DivValue. Distinguished from Quot by op-kw in lower-go (both render Go `/`)
	OpLt
	OpLte
	OpGt
	OpGte
	OpEq
	OpInc
	OpDec
	OpBitNot      // clojure.core/bit-not — integer bitwise complement
	OpPop         // discard top stack value; no result (OP_POP)
	OpReturn      // .Refs[0] = value
	OpBranch      // unconditional; .Aux = *BranchTarget
	OpBranchIf    // .Refs[0] = cond; .Aux = struct{True,False *BranchTarget}
	OpMakeClosure // .Refs[0] = *Func value (the func to wrap as a closure)
	OpPushClosed  // .Refs[0] = closure, .Refs[1] = value to attach
	OpTry         // .Refs[0] = body closure; then optional handler closure (binds the caught value), then optional finally closure; .Aux = {:has-handler bool :has-finally bool}. lower? -> TryOp delegates to try-assign-stmts (registered by ir.lower-go)
	OpDot         // .Refs[0] = obj; .Aux = field symbol; Go struct field selector obj.field (gogen_ir path only)
	OpDef         // .Refs[0] = var (Const aux=*vm.Var), optional .Refs[1] = value; interns + returns the var (2-ref also sets root)
)

// opInfo describes an Op's structural metadata.
type opInfo struct {
	name          string
	stackIn       int  // -1 = variable (decoded from Aux/arity)
	stackOut      int  // 0 or 1
	pure          bool // safe to CSE, fold, hoist
	terminator    bool // ends a basic block
	localCarrying bool // lowering materialises the result into a Go local
	inferFacet    bool // typeinfer facet reified on an ir.ops op-type
	lowerFacet    bool // lower-go facet reified on an ir.ops op-type
}

var opTable = [...]opInfo{
	OpInvalid:               {"INVALID", 0, 0, false, false, false, false, false},
	OpConst:                 {"Const", 0, 1, true, false, false, true, true},
	OpLoadArg:               {"LoadArg", 0, 1, true, false, false, true, false},
	OpLoadVar:               {"LoadVar", 0, 1, false, false, false, true, false},
	OpLoadClosed:            {"LoadClosed", 0, 1, true, false, false, true, false},
	OpBlockArg:              {"BlockArg", 0, 1, true, false, true, true, false},
	OpSetVar:                {"SetVar", 2, 1, false, false, false, false, false},
	OpCall:                  {"Call", -1, 1, false, false, true, false, false},
	OpTailCall:              {"TailCall", -1, 1, false, true, false, false, false},
	OpAdd:                   {"Add", 2, 1, true, false, true, true, false},
	OpSub:                   {"Sub", 2, 1, true, false, true, true, false},
	OpMul:                   {"Mul", 2, 1, true, false, true, true, false},
	OpBitAnd:                {"BitAnd", 2, 1, true, false, true, true, false},
	OpBitOr:                 {"BitOr", 2, 1, true, false, true, true, false},
	OpBitXor:                {"BitXor", 2, 1, true, false, true, true, false},
	OpBitAndNot:             {"BitAndNot", 2, 1, true, false, true, true, false},
	OpBitShiftLeft:          {"BitShiftLeft", 2, 1, true, false, true, true, false},
	OpBitShiftRight:         {"BitShiftRight", 2, 1, true, false, true, true, false},
	OpUnsignedBitShiftRight: {"UnsignedBitShiftRight", 2, 1, true, false, true, true, false},
	OpQuot:                  {"Quot", 2, 1, true, false, true, true, false},
	OpDiv:                   {"Div", 2, 1, true, false, true, true, false},
	OpLt:                    {"Lt", 2, 1, true, false, true, true, false},
	OpLte:                   {"Lte", 2, 1, true, false, true, true, false},
	OpGt:                    {"Gt", 2, 1, true, false, true, true, false},
	OpGte:                   {"Gte", 2, 1, true, false, true, true, false},
	OpEq:                    {"Eq", 2, 1, true, false, true, true, false},
	OpInc:                   {"Inc", 1, 1, true, false, true, true, false},
	OpDec:                   {"Dec", 1, 1, true, false, true, true, false},
	OpBitNot:                {"BitNot", 1, 1, true, false, true, true, false},
	OpPop:                   {"Pop", 1, 0, false, false, false, false, false},
	OpReturn:                {"Return", 1, 0, false, true, false, true, false},
	OpBranch:                {"Branch", 0, 0, false, true, false, true, false},
	OpBranchIf:              {"BranchIf", 1, 0, false, true, false, true, false},
	OpMakeClosure:           {"MakeClosure", 1, 1, false, false, false, false, false},
	OpPushClosed:            {"PushClosed", 2, 1, false, false, false, false, false},
	OpTry:                   {"Try", -1, 1, false, false, true, false, true},
	OpDot:                   {"Dot", 1, 1, false, false, true, false, false},
	OpDef:                   {"Def", -1, 1, false, false, true, false, false},
}

// String returns the op's display name (or "Op?" for an unknown op).
func (op Op) String() string {
	if int(op) < len(opTable) {
		return opTable[op].name
	}
	return "Op?"
}

// IsTerminator reports whether op ends a basic block.
func (op Op) IsTerminator() bool {
	if int(op) < len(opTable) {
		return opTable[op].terminator
	}
	return false
}

// IsPure reports whether op has no observable side effects.
func (op Op) IsPure() bool {
	if int(op) < len(opTable) {
		return opTable[op].pure
	}
	return false
}

// StackOut returns the number of values op pushes (0 or 1).
func (op Op) StackOut() int {
	if int(op) < len(opTable) {
		return opTable[op].stackOut
	}
	return 0
}

// LocalCarrying reports whether lowering materialises op's result into a Go local.
func (op Op) LocalCarrying() bool {
	if int(op) < len(opTable) {
		return opTable[op].localCarrying
	}
	return false
}

// InferFacet reports whether op's typeinfer facet is reified on an ir.ops op-type.
func (op Op) InferFacet() bool {
	if int(op) < len(opTable) {
		return opTable[op].inferFacet
	}
	return false
}

// LowerFacet reports whether op's lower-go facet is reified on an ir.ops op-type.
func (op Op) LowerFacet() bool {
	if int(op) < len(opTable) {
		return opTable[op].lowerFacet
	}
	return false
}

func isCheapMaterializeOp(op Op) bool {
	switch op {
	case OpConst, OpLoadArg, OpLoadVar, OpLoadClosed:
		return true
	default:
		return false
	}
}

func irOpToBytecode(op Op) int32 {
	switch op {
	case OpConst:
		return vm.OP_LOAD_CONST
	case OpLoadArg:
		return vm.OP_LOAD_ARG
	case OpLoadVar:
		return vm.OP_LOAD_VAR
	case OpLoadClosed:
		return vm.OP_LOAD_CLOSEDOVER
	case OpSetVar:
		return vm.OP_SET_VAR
	case OpCall:
		return vm.OP_INVOKE
	case OpTailCall:
		return vm.OP_TAIL_CALL
	case OpAdd:
		return vm.OP_ADD
	case OpSub:
		return vm.OP_SUB
	case OpMul:
		return vm.OP_MUL
	case OpBitAnd:
		return vm.OP_BIT_AND
	case OpBitOr:
		return vm.OP_BIT_OR
	case OpBitXor:
		return vm.OP_BIT_XOR
	case OpBitAndNot:
		return vm.OP_BIT_AND_NOT
	case OpBitShiftLeft:
		return vm.OP_BIT_SHIFT_LEFT
	case OpBitShiftRight:
		return vm.OP_BIT_SHIFT_RIGHT
	case OpUnsignedBitShiftRight:
		return vm.OP_UNSIGNED_BIT_SHIFT_RIGHT
	case OpQuot:
		return vm.OP_QUOT
	case OpDiv:
		return vm.OP_DIV
	case OpLt:
		return vm.OP_LT
	case OpLte:
		return vm.OP_LTE
	case OpGt:
		return vm.OP_GT
	case OpGte:
		return vm.OP_GTE
	case OpEq:
		return vm.OP_EQ
	case OpInc:
		return vm.OP_INC
	case OpDec:
		return vm.OP_DEC
	case OpBitNot:
		return vm.OP_BIT_NOT
	case OpReturn:
		return vm.OP_RETURN
	case OpBranch:
		return vm.OP_JUMP
	case OpBranchIf:
		return vm.OP_BRANCH_FALSE
	case OpMakeClosure:
		return vm.OP_MAKE_CLOSURE
	case OpPushClosed:
		return vm.OP_PUSH_CLOSEDOVER
	default:
		return vm.OP_NOOP
	}
}

func bytecodeToIROp(op int32) Op {
	switch op & 255 {
	case vm.OP_LOAD_CONST:
		return OpConst
	case vm.OP_LOAD_ARG:
		return OpLoadArg
	case vm.OP_LOAD_VAR:
		return OpLoadVar
	case vm.OP_LOAD_CLOSEDOVER:
		return OpLoadClosed
	case vm.OP_SET_VAR:
		return OpSetVar
	case vm.OP_INVOKE:
		return OpCall
	case vm.OP_TAIL_CALL:
		return OpTailCall
	case vm.OP_ADD:
		return OpAdd
	case vm.OP_SUB:
		return OpSub
	case vm.OP_MUL:
		return OpMul
	case vm.OP_BIT_AND:
		return OpBitAnd
	case vm.OP_BIT_OR:
		return OpBitOr
	case vm.OP_BIT_XOR:
		return OpBitXor
	case vm.OP_BIT_AND_NOT:
		return OpBitAndNot
	case vm.OP_BIT_SHIFT_LEFT:
		return OpBitShiftLeft
	case vm.OP_BIT_SHIFT_RIGHT:
		return OpBitShiftRight
	case vm.OP_UNSIGNED_BIT_SHIFT_RIGHT:
		return OpUnsignedBitShiftRight
	case vm.OP_QUOT:
		return OpQuot
	case vm.OP_DIV:
		return OpDiv
	case vm.OP_LT:
		return OpLt
	case vm.OP_LTE:
		return OpLte
	case vm.OP_GT:
		return OpGt
	case vm.OP_GTE:
		return OpGte
	case vm.OP_EQ:
		return OpEq
	case vm.OP_INC:
		return OpInc
	case vm.OP_DEC:
		return OpDec
	case vm.OP_BIT_NOT:
		return OpBitNot
	case vm.OP_RETURN:
		return OpReturn
	case vm.OP_JUMP:
		return OpBranch
	case vm.OP_BRANCH_FALSE:
		return OpBranchIf
	case vm.OP_MAKE_CLOSURE:
		return OpMakeClosure
	case vm.OP_PUSH_CLOSEDOVER:
		return OpPushClosed
	default:
		return OpInvalid
	}
}

var opKeywordNames = []string{"invalid", "const", "load-arg", "load-var", "load-closed", "block-arg", "set-var", "call", "tail-call", "add", "sub", "mul", "bit-and", "bit-or", "bit-xor", "bit-and-not", "bit-shift-left", "bit-shift-right", "unsigned-bit-shift-right", "quot", "div", "lt", "lte", "gt", "gte", "eq", "inc", "dec", "bit-not", "pop", "return", "branch", "branch-if", "make-closure", "push-closed", "try", "dot", "def"}

// OpKeywords returns every catalogued op as its kebab-case keyword name, in Op order.
func OpKeywords() []string { return opKeywordNames }

func opByKeywordExact(name string) (Op, bool) {
	switch name {
	case "invalid":
		return OpInvalid, true
	case "const":
		return OpConst, true
	case "load-arg":
		return OpLoadArg, true
	case "load-var":
		return OpLoadVar, true
	case "load-closed":
		return OpLoadClosed, true
	case "block-arg":
		return OpBlockArg, true
	case "set-var":
		return OpSetVar, true
	case "call":
		return OpCall, true
	case "tail-call":
		return OpTailCall, true
	case "add":
		return OpAdd, true
	case "sub":
		return OpSub, true
	case "mul":
		return OpMul, true
	case "bit-and":
		return OpBitAnd, true
	case "bit-or":
		return OpBitOr, true
	case "bit-xor":
		return OpBitXor, true
	case "bit-and-not":
		return OpBitAndNot, true
	case "bit-shift-left":
		return OpBitShiftLeft, true
	case "bit-shift-right":
		return OpBitShiftRight, true
	case "unsigned-bit-shift-right":
		return OpUnsignedBitShiftRight, true
	case "quot":
		return OpQuot, true
	case "div":
		return OpDiv, true
	case "lt":
		return OpLt, true
	case "lte":
		return OpLte, true
	case "gt":
		return OpGt, true
	case "gte":
		return OpGte, true
	case "eq":
		return OpEq, true
	case "inc":
		return OpInc, true
	case "dec":
		return OpDec, true
	case "bit-not":
		return OpBitNot, true
	case "pop":
		return OpPop, true
	case "return":
		return OpReturn, true
	case "branch":
		return OpBranch, true
	case "branch-if":
		return OpBranchIf, true
	case "make-closure":
		return OpMakeClosure, true
	case "push-closed":
		return OpPushClosed, true
	case "try":
		return OpTry, true
	case "dot":
		return OpDot, true
	case "def":
		return OpDef, true
	default:
		return OpInvalid, false
	}
}
