#!/bin/sh
# Content-check every committed generated artifact, then verify the gitignored
# gogen_ir tree compiles and dispatches natively.
#
# This gate is VCS-agnostic by design: the repository is also used from jj
# workspaces without a .git directory. It restores the tracked files to exactly
# the bytes it found on success, failure, generator error, or interruption.

set -u

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root" || exit 1

# generate.lg produces exactly this set of committed artifacts. When another
# committed output is added, update this list and the generator together.
tracked_files='pkg/ir/op_generated.go
pkg/rt/ir_bridge_generated.go
pkg/rt/core/ir/data/generated.lg
pkg/rt/zz_primitives_generated.go
pkg/rt/corefns/zz_primitives_generated.go
pkg/rt/core_compiled.lgb'

# generated.sums is refreshed as a side effect of bundle generation. Preserve
# it to keep this check non-mutating, but do not compare it here: the separate
# check-generated-manifest gate validates the digest.
preserved_files="$tracked_files
pkg/rt/generated.sums"

tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/letgo-check-generated.XXXXXX") || exit 1
stash_complete=0

cleanup() {
	rc=$?
	trap - EXIT HUP INT TERM

	if [ "$stash_complete" -eq 1 ]; then
		restore_failed=0
		for file in $preserved_files; do
			if ! cp "$tmp_dir/$file" "$file"; then
				echo "ERROR: failed to restore $file from $tmp_dir" >&2
				restore_failed=1
			fi
		done
		if [ "$restore_failed" -ne 0 ]; then
			echo "ERROR: generated-file recovery copy preserved at $tmp_dir" >&2
			exit 1
		fi
	fi

	rm -rf "$tmp_dir"
	exit "$rc"
}

trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

for file in $preserved_files; do
	mkdir -p "$tmp_dir/$(dirname -- "$file")" || exit 1
	cp "$file" "$tmp_dir/$file" || exit 1
done
stash_complete=1

echo ">> regenerate every committed artifact through the full 'make generate'"
make_bin=${MAKE:-make}
if ! "$make_bin" --no-print-directory generate >/dev/null; then
	echo "ERROR: 'make generate' failed — see the generator output above."
	exit 1
fi

stale=0
for file in $tracked_files; do
	if cmp -s "$file" "$tmp_dir/$file"; then
		echo "OK: $file in lockstep with source."
	else
		echo "ERROR: $file is stale — the regenerated bytes differ."
		stale=1
	fi
done

if [ "$stale" -ne 0 ]; then
	echo "       Your working tree was left exactly as the gate found it."
	echo "       Run 'make generate' and commit the regenerated files."
	exit 1
fi

echo ">> lowered tree: compile + dispatch natively under -tags gogen_ir"
go build -tags gogen_ir ./pkg/rt/... || exit 1

out=$(printf '%s\n' '(require (quote ir.passes.dce)) (println "DCE-TYPE:" (type ir.passes.dce/dce))' \
	| go run -tags gogen_ir . /dev/stdin 2>&1)
if printf '%s\n' "$out" | grep -q "DCE-TYPE: let-go.lang.NativeFn"; then
	echo "OK: core_go_lowered/ compiles + dispatches natively (dce -> NativeFn)."
else
	echo "FAIL: ir.passes.dce/dce did not dispatch to a NativeFn override"
	printf '%s\n' "$out" | tail -5
	exit 1
fi
