#!/usr/bin/env bash
# Generate pkg/rt/ir_bridge_generated.go from examples/go-gen/ir_bridge.lg.
#
# Pipeline mirrors scripts/generate-ir-ops.sh:
#   1. write header (copyright, "DO NOT EDIT", package, imports) to tmp
#   2. run ./lg on the generator, append stdout
#   3. gofmt → final output
#
# Output: pkg/rt/ir_bridge_generated.go.

set -euo pipefail

cd "$(dirname "$0")/.."

if [ ! -x ./lg ]; then
  echo "error: ./lg binary not found; run 'make build' first" >&2
  exit 1
fi

OUT=pkg/rt/ir_bridge_generated.go
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<'EOF'
/*
 * Copyright (c) 2026 Norman Nunley, Jr <nnunley@gmail.com>
 * Part of the let-go project; see CONTRIBUTORS for full list of authors.
 * SPDX-License-Identifier: MIT
 */

// Code generated by examples/go-gen/ir_bridge.lg. DO NOT EDIT.
//
// Lisp/Go bridge primitives for IR types. See:
//   docs/superpowers/specs/2026-05-22-defgostruct.md
//
// Regenerate: make generate-ir-bridge

package rt

import (
	"fmt"

	"github.com/nooga/let-go/pkg/ir"
	"github.com/nooga/let-go/pkg/vm"
)

// Suppress unused-import warnings if the generator emits no primitives
// that touch these packages.
var _ = ir.OpInvalid
var _ = fmt.Errorf

EOF

./lg -source-paths examples/go-gen examples/go-gen/ir_bridge.lg >> "$TMP"

gofmt "$TMP" > "$OUT"

echo "wrote $OUT"
