#!/usr/bin/env bash
# Generate pkg/ir/op_generated.go from examples/go-gen/ir_ops.lg.
#
# This is the "metadata only" piece of the IR defop sweep: the
# const block + opTable + accessor methods. The other op switches
# (irOpToBytecode, bytecodeToIROp, isCheapMaterializeOp, instStride)
# live in lower.go / build.go and are filed as separate follow-ups.
#
# The generator uses gogen for the opTable composite literal (where
# field alignment matters and the spec→Go mapping is non-trivial)
# and emits everything else as text. The const block in particular
# can't go through gogen because there's no walker for `const ( ... )`
# with iota; emitting it as text is straightforward.
#
# Output is piped through gofmt so the table literal gets the
# canonical multi-line layout instead of the one-line render that
# go/format.Node produces.

set -euo pipefail

cd "$(dirname "$0")/.."

if [ ! -x ./lg ]; then
  echo "error: ./lg binary not found; run 'make build' first" >&2
  exit 1
fi

OUT=pkg/ir/op_generated.go
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<'EOF'
/*
 * Copyright (c) 2026 Norman Nunley, Jr <nnunley@gmail.com>
 * Part of the let-go project; see CONTRIBUTORS for full list of authors.
 * SPDX-License-Identifier: MIT
 */

// Code generated by examples/go-gen/ir_ops.lg. DO NOT EDIT.
//
// Package ir — indexed-RPN, block-parameter SSA IR for let-go.
//
// Design references:
//   - Burak Emir, "Indexed Reverse Polish Notation" (burakemir.ch)
//   - Carbon Language semantic IR (toolchain/sem_ir)
//   - Swift SIL, Cranelift, MLIR — all use block-parameter SSA
//
// Op kinds are catalogued in examples/go-gen/ir_ops.lg. Each op
// declares its operand arity (number of input values popped from the
// RPN-walk stack), the number of values it pushes (0 or 1), and a
// "pure" flag controlling whether optimization passes may CSE / fold
// / hoist it.

package ir

import "github.com/nooga/let-go/pkg/vm"

EOF

./lg -source-paths examples/go-gen examples/go-gen/ir_ops.lg >> "$TMP"

# Pipe through gofmt so the table literal and const block get canonical
# layout (multi-line, aligned). gogen's render is correct Go but uses
# go/format.Node's "compact" output for embedded nodes.
gofmt "$TMP" > "$OUT"

echo "wrote $OUT"
