// Code generated by `lginterop -packages github.com/nooga/let-go/pkg/glplat`. DO NOT EDIT.
package rt

import (
	"fmt"

	glplat "github.com/nooga/let-go/pkg/glplat"
	"github.com/nooga/let-go/pkg/vm"
)

func init() { RegisterInstaller(installGlplatNS) }

func wrapGlplatInit(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 3 {
		return vm.NIL, fmt.Errorf("glplat/Init: expected 3 args, got %d", len(vs))
	}
	width, _ := vm.ToInt(vs[0])
	height, _ := vm.ToInt(vs[1])
	titleStr, ok := vs[2].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("glplat/Init: arg 2 must be String, got %s", vs[2].Type().Name())
	}
	title := string(titleStr)
	err := glplat.Init(int(width), int(height), title)
	if err != nil {
		return vm.NIL, err
	}
	return vm.NIL, nil
}

func wrapGlplatLoadTextureFile(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 1 {
		return vm.NIL, fmt.Errorf("glplat/LoadTextureFile: expected 1 arg, got %d", len(vs))
	}
	pathStr, ok := vs[0].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("glplat/LoadTextureFile: arg 0 must be String, got %s", vs[0].Type().Name())
	}
	path := string(pathStr)
	texID, err := glplat.LoadTextureFile(path)
	if err != nil {
		return vm.NIL, err
	}
	return vm.Int(int64(texID)), nil
}

func wrapGlplatLoadTextureRGBA(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 3 {
		return vm.NIL, fmt.Errorf("glplat/LoadTextureRGBA: expected 3 args, got %d", len(vs))
	}

	// Unbox pixels vector
	var pixels []byte
	if seq, ok := vs[0].(vm.Sequable); ok {
		for s := seq.Seq(); s != nil; s = s.Next() {
			val := s.First()
			n, _ := vm.ToInt(val)
			pixels = append(pixels, byte(n))
		}
	} else {
		return vm.NIL, fmt.Errorf("glplat/LoadTextureRGBA: pixels must be sequable")
	}

	w, _ := vm.ToInt(vs[1])
	h, _ := vm.ToInt(vs[2])
	texID, err := glplat.LoadTextureRGBA(pixels, int(w), int(h))
	if err != nil {
		return vm.NIL, err
	}
	return vm.Int(int64(texID)), nil
}

func wrapGlplatSetMatrix(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 1 {
		return vm.NIL, fmt.Errorf("glplat/SetMatrix: expected 1 arg, got %d", len(vs))
	}

	// Unbox matrix vector (16 floats)
	var m []float64
	if seq, ok := vs[0].(vm.Sequable); ok {
		for s := seq.Seq(); s != nil; s = s.Next() {
			val := s.First()
			f, _ := vm.ToFloat(val)
			m = append(m, f)
		}
	} else {
		return vm.NIL, fmt.Errorf("glplat/SetMatrix: matrix must be sequable")
	}

	if len(m) != 16 {
		return vm.NIL, fmt.Errorf("glplat/SetMatrix: matrix must have 16 elements, got %d", len(m))
	}

	err := glplat.SetMatrix(m)
	if err != nil {
		return vm.NIL, err
	}
	return vm.NIL, nil
}

func wrapGlplatSubmitTriangles(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 2 {
		return vm.NIL, fmt.Errorf("glplat/SubmitTriangles: expected 2 args, got %d", len(vs))
	}

	texID, _ := vm.ToInt(vs[0])

	// Unbox verts vector (9n floats)
	var verts []float64
	if seq, ok := vs[1].(vm.Sequable); ok {
		for s := seq.Seq(); s != nil; s = s.Next() {
			val := s.First()
			f, _ := vm.ToFloat(val)
			verts = append(verts, f)
		}
	} else {
		return vm.NIL, fmt.Errorf("glplat/SubmitTriangles: verts must be sequable")
	}

	if len(verts)%9 != 0 {
		return vm.NIL, fmt.Errorf("glplat/SubmitTriangles: verts length must be divisible by 9, got %d", len(verts))
	}

	err := glplat.SubmitTriangles(int(texID), verts)
	if err != nil {
		return vm.NIL, err
	}
	return vm.NIL, nil
}

func wrapGlplatPollInputEvents(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 0 {
		return vm.NIL, fmt.Errorf("glplat/PollInputEvents: expected 0 args, got %d", len(vs))
	}
	events := glplat.PollInputEvents()
	vals := make([]vm.Value, len(events))
	for i, e := range events {
		vals[i] = vm.String(e)
	}
	return vm.NewArrayVector(vals), nil
}

func wrapGlplatShouldClose(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 0 {
		return vm.NIL, fmt.Errorf("glplat/ShouldClose: expected 0 args, got %d", len(vs))
	}
	result := glplat.ShouldClose()
	return vm.Boolean(result), nil
}

func wrapGlplatPollEvents(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 0 {
		return vm.NIL, fmt.Errorf("glplat/PollEvents: expected 0 args, got %d", len(vs))
	}
	glplat.PollEvents()
	return vm.NIL, nil
}

func wrapGlplatBeginFrame(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 3 {
		return vm.NIL, fmt.Errorf("glplat/BeginFrame: expected 3 args, got %d", len(vs))
	}
	r, _ := vm.ToFloat(vs[0])
	g, _ := vm.ToFloat(vs[1])
	b, _ := vm.ToFloat(vs[2])
	glplat.BeginFrame(r, g, b)
	return vm.NIL, nil
}

func wrapGlplatEndFrame(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 0 {
		return vm.NIL, fmt.Errorf("glplat/EndFrame: expected 0 args, got %d", len(vs))
	}
	glplat.EndFrame()
	return vm.NIL, nil
}

func wrapGlplatTime(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 0 {
		return vm.NIL, fmt.Errorf("glplat/Time: expected 0 args, got %d", len(vs))
	}
	result := glplat.Time()
	return vm.Float(result), nil
}

func wrapGlplatTerminate(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 0 {
		return vm.NIL, fmt.Errorf("glplat/Terminate: expected 0 args, got %d", len(vs))
	}
	err := glplat.Terminate()
	if err != nil {
		return vm.NIL, err
	}
	return vm.NIL, nil
}

func wrapGlplatTextureSize(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 1 {
		return vm.NIL, fmt.Errorf("glplat/TextureSize: expected 1 arg, got %d", len(vs))
	}
	id, _ := vm.ToInt(vs[0])
	w, h := glplat.TextureSize(int(id))
	return vm.NewArrayVector([]vm.Value{vm.Int(int64(w)), vm.Int(int64(h))}), nil
}

func wrapGlplatWindowSize(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 0 {
		return vm.NIL, fmt.Errorf("glplat/WindowSize: expected 0 args, got %d", len(vs))
	}
	w, h := glplat.WindowSize()
	return vm.NewArrayVector([]vm.Value{vm.Int(int64(w)), vm.Int(int64(h))}), nil
}

func wrapGlplatFontLoad(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 1 {
		return vm.NIL, fmt.Errorf("glplat/FontLoad: expected 1 arg, got %d", len(vs))
	}
	pathStr, ok := vs[0].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("glplat/FontLoad: arg 0 must be String, got %s", vs[0].Type().Name())
	}
	path := string(pathStr)
	fontID, err := glplat.FontLoad(path)
	if err != nil {
		return vm.NIL, err
	}
	return vm.Int(int64(fontID)), nil
}

func wrapGlplatFontHasGlyph(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 2 {
		return vm.NIL, fmt.Errorf("glplat/FontHasGlyph: expected 2 args, got %d", len(vs))
	}
	fontID, _ := vm.ToInt(vs[0])
	chStr, ok := vs[1].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("glplat/FontHasGlyph: arg 1 must be String, got %s", vs[1].Type().Name())
	}
	ch := string(chStr)
	result := glplat.FontHasGlyph(int(fontID), ch)
	return vm.Boolean(result), nil
}

func wrapGlplatFontRasterizeCell(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 4 {
		return vm.NIL, fmt.Errorf("glplat/FontRasterizeCell: expected 4 args, got %d", len(vs))
	}
	fontID, _ := vm.ToInt(vs[0])
	chStr, ok := vs[1].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("glplat/FontRasterizeCell: arg 1 must be String, got %s", vs[1].Type().Name())
	}
	ch := string(chStr)
	cellW, _ := vm.ToInt(vs[2])
	cellH, _ := vm.ToInt(vs[3])

	alphas, err := glplat.FontRasterizeCell(int(fontID), ch, int(cellW), int(cellH))
	if err != nil {
		return vm.NIL, err
	}

	// Convert float64 array to lg vector
	vals := make([]vm.Value, len(alphas))
	for i, a := range alphas {
		vals[i] = vm.Float(a)
	}
	return vm.NewArrayVector(vals), nil
}

func wrapGlplatSaveGlyphAtlasPNG(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 4 {
		return vm.NIL, fmt.Errorf("glplat/SaveGlyphAtlasPNG: expected 4 args, got %d", len(vs))
	}
	pathStr, ok := vs[0].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("glplat/SaveGlyphAtlasPNG: arg 0 must be String, got %s", vs[0].Type().Name())
	}
	path := string(pathStr)

	w, _ := vm.ToInt(vs[1])
	h, _ := vm.ToInt(vs[2])

	// Unbox alphas vector
	var alphas []float64
	if seq, ok := vs[3].(vm.Sequable); ok {
		for s := seq.Seq(); s != nil; s = s.Next() {
			val := s.First()
			f, _ := vm.ToFloat(val)
			alphas = append(alphas, f)
		}
	} else {
		return vm.NIL, fmt.Errorf("glplat/SaveGlyphAtlasPNG: alphas must be sequable")
	}

	err := glplat.SaveGlyphAtlasPNG(path, int(w), int(h), alphas)
	if err != nil {
		return vm.NIL, err
	}
	return vm.NIL, nil
}

func installGlplatNS() {
	ns := vm.NewNamespace("glplat")

	initFn, _ := vm.NativeFnType.Wrap(wrapGlplatInit)
	ns.Def("Init", initFn)

	loadTexFileFn, _ := vm.NativeFnType.Wrap(wrapGlplatLoadTextureFile)
	ns.Def("LoadTextureFile", loadTexFileFn)

	loadTexRGBAFn, _ := vm.NativeFnType.Wrap(wrapGlplatLoadTextureRGBA)
	ns.Def("LoadTextureRGBA", loadTexRGBAFn)

	setMatFn, _ := vm.NativeFnType.Wrap(wrapGlplatSetMatrix)
	ns.Def("SetMatrix", setMatFn)

	submitTriFn, _ := vm.NativeFnType.Wrap(wrapGlplatSubmitTriangles)
	ns.Def("SubmitTriangles", submitTriFn)

	pollInputFn, _ := vm.NativeFnType.Wrap(wrapGlplatPollInputEvents)
	ns.Def("PollInputEvents", pollInputFn)

	shouldCloseFn, _ := vm.NativeFnType.Wrap(wrapGlplatShouldClose)
	ns.Def("ShouldClose", shouldCloseFn)

	pollEventsFn, _ := vm.NativeFnType.Wrap(wrapGlplatPollEvents)
	ns.Def("PollEvents", pollEventsFn)

	beginFrameFn, _ := vm.NativeFnType.Wrap(wrapGlplatBeginFrame)
	ns.Def("BeginFrame", beginFrameFn)

	endFrameFn, _ := vm.NativeFnType.Wrap(wrapGlplatEndFrame)
	ns.Def("EndFrame", endFrameFn)

	timeFn, _ := vm.NativeFnType.Wrap(wrapGlplatTime)
	ns.Def("Time", timeFn)

	terminateFn, _ := vm.NativeFnType.Wrap(wrapGlplatTerminate)
	ns.Def("Terminate", terminateFn)

	texSizeFn, _ := vm.NativeFnType.Wrap(wrapGlplatTextureSize)
	ns.Def("TextureSize", texSizeFn)

	winSizeFn, _ := vm.NativeFnType.Wrap(wrapGlplatWindowSize)
	ns.Def("WindowSize", winSizeFn)

	fontLoadFn, _ := vm.NativeFnType.Wrap(wrapGlplatFontLoad)
	ns.Def("FontLoad", fontLoadFn)

	fontHasGlyphFn, _ := vm.NativeFnType.Wrap(wrapGlplatFontHasGlyph)
	ns.Def("FontHasGlyph", fontHasGlyphFn)

	fontRasterizeCellFn, _ := vm.NativeFnType.Wrap(wrapGlplatFontRasterizeCell)
	ns.Def("FontRasterizeCell", fontRasterizeCellFn)

	saveGlyphAtlasPNGFn, _ := vm.NativeFnType.Wrap(wrapGlplatSaveGlyphAtlasPNG)
	ns.Def("SaveGlyphAtlasPNG", saveGlyphAtlasPNGFn)

	RegisterNS(ns)
}
