// Code generated by `lginterop -packages github.com/zeebo/xxh3 -opaque-structs`. DO NOT EDIT.
package rt

import (
	"github.com/nooga/let-go/pkg/vm"
	xxh3 "github.com/zeebo/xxh3"
)

func init() {
	RegisterInstaller(installXxh3NS)
}
func installXxh3NS() {
	ns := vm.NewNamespace("xxh3")
	ns.Def("Hash", vm.MustBox(xxh3.Hash))
	ns.Def("Hash128", vm.MustBox(xxh3.Hash128))
	ns.Def("Hash128Seed", vm.MustBox(xxh3.Hash128Seed))
	ns.Def("HashSeed", vm.MustBox(xxh3.HashSeed))
	ns.Def("HashString", vm.MustBox(xxh3.HashString))
	ns.Def("HashString128", vm.MustBox(xxh3.HashString128))
	ns.Def("HashString128Seed", vm.MustBox(xxh3.HashString128Seed))
	ns.Def("HashStringSeed", vm.MustBox(xxh3.HashStringSeed))
	ns.Def("New", vm.MustBox(xxh3.New))
	ns.Def("New128", vm.MustBox(xxh3.New128))
	ns.Def("NewSeed", vm.MustBox(xxh3.NewSeed))
	ns.Def("NewSeed128", vm.MustBox(xxh3.NewSeed128))
	RegisterNS(ns)
}
