/*
 * Copyright (c) 2026 Norman Nunley, Jr <nnunley@gmail.com>
 * Part of the let-go project; see CONTRIBUTORS for full list of authors.
 * SPDX-License-Identifier: MIT
 */

// Code generated by examples/go-gen/ir_bridge.lg. DO NOT EDIT.
//
// Lisp/Go bridge primitives for IR types. See:
//   docs/superpowers/specs/2026-05-22-defgostruct.md
//
// Regenerate: make generate-ir-bridge

package rt

import (
	"fmt"

	"github.com/nooga/let-go/pkg/ir"
	"github.com/nooga/let-go/pkg/vm"
)

// Suppress unused-import warnings if the generator emits no primitives
// that touch these packages.
var _ = ir.OpInvalid
var _ = fmt.Errorf

// installIRBridgeBuiltins creates the `ir` namespace and registers
// the generated bridge primitives in it. Called from installLangNS
// in lang.go.
func installIRBridgeBuiltins() {
	ns := vm.NewNamespace("ir")

	// ir.Function primitives
	fn_op_terminator_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 1 {
			return vm.NIL, fmt.Errorf("ir/op-terminator?: expected (OpKw), got %d args", len(vs))
		}
		arg0Kw, ok0 := vs[0].(vm.Keyword)
		if !ok0 {
			return vm.NIL, fmt.Errorf("ir/op-terminator?: arg 0 must be Keyword, got %s", vs[0].Type().Name())
		}
		arg0, okOp0 := ir.OpByKeyword(string(arg0Kw))
		if !okOp0 {
			return vm.NIL, fmt.Errorf("ir/op-terminator?: unknown op %s", string(arg0Kw))
		}
		return vm.Boolean(arg0.IsTerminator()), nil
	})
	ns.Def("op-terminator?", fn_op_terminator_Fn)
	fn_op_pure_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 1 {
			return vm.NIL, fmt.Errorf("ir/op-pure?: expected (OpKw), got %d args", len(vs))
		}
		arg0Kw, ok0 := vs[0].(vm.Keyword)
		if !ok0 {
			return vm.NIL, fmt.Errorf("ir/op-pure?: arg 0 must be Keyword, got %s", vs[0].Type().Name())
		}
		arg0, okOp0 := ir.OpByKeyword(string(arg0Kw))
		if !okOp0 {
			return vm.NIL, fmt.Errorf("ir/op-pure?: unknown op %s", string(arg0Kw))
		}
		return vm.Boolean(arg0.IsPure()), nil
	})
	ns.Def("op-pure?", fn_op_pure_Fn)
	fn_op_cheap_load_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 1 {
			return vm.NIL, fmt.Errorf("ir/op-cheap-load?: expected (OpKw), got %d args", len(vs))
		}
		arg0Kw, ok0 := vs[0].(vm.Keyword)
		if !ok0 {
			return vm.NIL, fmt.Errorf("ir/op-cheap-load?: arg 0 must be Keyword, got %s", vs[0].Type().Name())
		}
		arg0, okOp0 := ir.OpByKeyword(string(arg0Kw))
		if !okOp0 {
			return vm.NIL, fmt.Errorf("ir/op-cheap-load?: unknown op %s", string(arg0Kw))
		}
		return vm.Boolean(ir.IsCheapMaterializeOp(arg0)), nil
	})
	ns.Def("op-cheap-load?", fn_op_cheap_load_Fn)
	fn_op_stack_out_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 1 {
			return vm.NIL, fmt.Errorf("ir/op-stack-out: expected (OpKw), got %d args", len(vs))
		}
		arg0Kw, ok0 := vs[0].(vm.Keyword)
		if !ok0 {
			return vm.NIL, fmt.Errorf("ir/op-stack-out: arg 0 must be Keyword, got %s", vs[0].Type().Name())
		}
		arg0, okOp0 := ir.OpByKeyword(string(arg0Kw))
		if !okOp0 {
			return vm.NIL, fmt.Errorf("ir/op-stack-out: unknown op %s", string(arg0Kw))
		}
		return vm.MakeInt(arg0.StackOut()), nil
	})
	ns.Def("op-stack-out", fn_op_stack_out_Fn)

	// vm.CodeChunk primitives
	chunk_new_consts_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 0 {
			return vm.NIL, fmt.Errorf("ir/new-consts: expected (), got %d args", len(vs))
		}
		return vm.NewBoxed(vm.NewConsts()), nil
	})
	ns.Def("new-consts", chunk_new_consts_Fn)
	chunk_new_chunk_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 1 {
			return vm.NIL, fmt.Errorf("ir/new-chunk: expected (BoxedAuxOrNil), got %d args", len(vs))
		}
		arg0Val := vs[0]
		var arg0 interface{}
		if arg0Val == vm.NIL {
			arg0 = nil
		} else if b, isBoxed := arg0Val.(*vm.Boxed); isBoxed {
			arg0 = b.Unbox()
		} else {
			arg0 = arg0Val
		}
		consts, ok := arg0.(*vm.Consts)
		if !ok {
			return vm.NIL, fmt.Errorf("ir/new-chunk: arg 0 must be boxed *vm.Consts, got %T", arg0)
		}
		return vm.NewBoxed(vm.NewCodeChunk(consts)), nil
	})
	ns.Def("new-chunk", chunk_new_chunk_Fn)
	chunk_new_source_info_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 5 {
			return vm.NIL, fmt.Errorf("ir/new-source-info: expected (String Int Int Int Int), got %d args", len(vs))
		}
		arg0Str, ok0 := vs[0].(vm.String)
		if !ok0 {
			return vm.NIL, fmt.Errorf("ir/new-source-info: arg 0 must be String, got %s", vs[0].Type().Name())
		}
		arg0 := string(arg0Str)
		arg1Int, ok1 := vs[1].(vm.Int)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/new-source-info: arg 1 must be Int, got %s", vs[1].Type().Name())
		}
		arg1 := int(arg1Int)
		arg2Int, ok2 := vs[2].(vm.Int)
		if !ok2 {
			return vm.NIL, fmt.Errorf("ir/new-source-info: arg 2 must be Int, got %s", vs[2].Type().Name())
		}
		arg2 := int(arg2Int)
		arg3Int, ok3 := vs[3].(vm.Int)
		if !ok3 {
			return vm.NIL, fmt.Errorf("ir/new-source-info: arg 3 must be Int, got %s", vs[3].Type().Name())
		}
		arg3 := int(arg3Int)
		arg4Int, ok4 := vs[4].(vm.Int)
		if !ok4 {
			return vm.NIL, fmt.Errorf("ir/new-source-info: arg 4 must be Int, got %s", vs[4].Type().Name())
		}
		arg4 := int(arg4Int)
		return vm.NewBoxed(vm.SourceInfo{File: arg0, Line: arg1, Column: arg2, EndLine: arg3, EndColumn: arg4}), nil
	})
	ns.Def("new-source-info", chunk_new_source_info_Fn)
	chunk_chunk_length_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 1 {
			return vm.NIL, fmt.Errorf("ir/chunk-length: expected (Self), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-length: %v", err)
		}
		return vm.MakeInt(arg0.Length()), nil
	})
	ns.Def("chunk-length", chunk_chunk_length_Fn)
	chunk_chunk_emit_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 3 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit: expected (Self OpKw Int), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-emit: %v", err)
		}
		arg1Kw, ok1 := vs[1].(vm.Keyword)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit: arg 1 must be Keyword, got %s", vs[1].Type().Name())
		}
		arg1, okOp1 := ir.OpByKeyword(string(arg1Kw))
		if !okOp1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit: unknown op %s", string(arg1Kw))
		}
		arg2Int, ok2 := vs[2].(vm.Int)
		if !ok2 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit: arg 2 must be Int, got %s", vs[2].Type().Name())
		}
		arg2 := int(arg2Int)
		arg0.Append(ir.IROpToBytecode(arg1) | int32(arg2<<16))
		return vm.NIL, nil
	})
	ns.Def("chunk-emit", chunk_chunk_emit_Fn)
	chunk_chunk_emit_with_arg_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 4 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-with-arg: expected (Self OpKw Int Int), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-with-arg: %v", err)
		}
		arg1Kw, ok1 := vs[1].(vm.Keyword)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-with-arg: arg 1 must be Keyword, got %s", vs[1].Type().Name())
		}
		arg1, okOp1 := ir.OpByKeyword(string(arg1Kw))
		if !okOp1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-with-arg: unknown op %s", string(arg1Kw))
		}
		arg2Int, ok2 := vs[2].(vm.Int)
		if !ok2 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-with-arg: arg 2 must be Int, got %s", vs[2].Type().Name())
		}
		arg2 := int(arg2Int)
		arg3Int, ok3 := vs[3].(vm.Int)
		if !ok3 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-with-arg: arg 3 must be Int, got %s", vs[3].Type().Name())
		}
		arg3 := int(arg3Int)
		arg0.Append(ir.IROpToBytecode(arg1) | int32(arg2<<16))
		arg0.Append32(arg3)
		return vm.NIL, nil
	})
	ns.Def("chunk-emit-with-arg", chunk_chunk_emit_with_arg_Fn)
	chunk_chunk_emit_placeholder_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 3 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-placeholder: expected (Self OpKw Int), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-placeholder: %v", err)
		}
		arg1Kw, ok1 := vs[1].(vm.Keyword)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-placeholder: arg 1 must be Keyword, got %s", vs[1].Type().Name())
		}
		arg1, okOp1 := ir.OpByKeyword(string(arg1Kw))
		if !okOp1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-placeholder: unknown op %s", string(arg1Kw))
		}
		arg2Int, ok2 := vs[2].(vm.Int)
		if !ok2 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-placeholder: arg 2 must be Int, got %s", vs[2].Type().Name())
		}
		arg2 := int(arg2Int)
		arg0.Append(ir.IROpToBytecode(arg1) | int32(arg2<<16))
		argIP := arg0.Length()
		arg0.Append32(0)
		return vm.MakeInt(argIP), nil
	})
	ns.Def("chunk-emit-placeholder", chunk_chunk_emit_placeholder_Fn)
	chunk_chunk_emit_dup_nth_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 3 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-dup-nth: expected (Self Int Int), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-dup-nth: %v", err)
		}
		arg1Int, ok1 := vs[1].(vm.Int)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-dup-nth: arg 1 must be Int, got %s", vs[1].Type().Name())
		}
		arg1 := int(arg1Int)
		arg2Int, ok2 := vs[2].(vm.Int)
		if !ok2 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-dup-nth: arg 2 must be Int, got %s", vs[2].Type().Name())
		}
		arg2 := int(arg2Int)
		arg0.Append(vm.OP_DUP_NTH | int32(arg1<<16))
		arg0.Append32(arg2)
		return vm.NIL, nil
	})
	ns.Def("chunk-emit-dup-nth", chunk_chunk_emit_dup_nth_Fn)
	chunk_chunk_emit_recur_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 4 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-recur: expected (Self Int Int Int), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-recur: %v", err)
		}
		arg1Int, ok1 := vs[1].(vm.Int)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-recur: arg 1 must be Int, got %s", vs[1].Type().Name())
		}
		arg1 := int(arg1Int)
		arg2Int, ok2 := vs[2].(vm.Int)
		if !ok2 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-recur: arg 2 must be Int, got %s", vs[2].Type().Name())
		}
		arg2 := int(arg2Int)
		arg3Int, ok3 := vs[3].(vm.Int)
		if !ok3 {
			return vm.NIL, fmt.Errorf("ir/chunk-emit-recur: arg 3 must be Int, got %s", vs[3].Type().Name())
		}
		arg3 := int(arg3Int)
		arg0.Append(vm.OP_RECUR | int32(arg1<<16))
		offIP := arg0.Length()
		arg0.Append32(0)
		arg0.Append32(arg2)
		arg0.Append32(arg3)
		return vm.MakeInt(offIP), nil
	})
	ns.Def("chunk-emit-recur", chunk_chunk_emit_recur_Fn)
	chunk_chunk_update_bang_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 3 {
			return vm.NIL, fmt.Errorf("ir/chunk-update!: expected (Self Int Int), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-update!: %v", err)
		}
		arg1Int, ok1 := vs[1].(vm.Int)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/chunk-update!: arg 1 must be Int, got %s", vs[1].Type().Name())
		}
		arg1 := int(arg1Int)
		arg2Int, ok2 := vs[2].(vm.Int)
		if !ok2 {
			return vm.NIL, fmt.Errorf("ir/chunk-update!: arg 2 must be Int, got %s", vs[2].Type().Name())
		}
		arg2 := int(arg2Int)
		arg0.Update32(arg1, int32(arg2))
		return vm.NIL, nil
	})
	ns.Def("chunk-update!", chunk_chunk_update_bang_Fn)
	chunk_chunk_max_stack_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 1 {
			return vm.NIL, fmt.Errorf("ir/chunk-max-stack: expected (Self), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-max-stack: %v", err)
		}
		return vm.MakeInt(arg0.MaxStack()), nil
	})
	ns.Def("chunk-max-stack", chunk_chunk_max_stack_Fn)
	chunk_chunk_set_max_stack_bang_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 2 {
			return vm.NIL, fmt.Errorf("ir/chunk-set-max-stack!: expected (Self Int), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-set-max-stack!: %v", err)
		}
		arg1Int, ok1 := vs[1].(vm.Int)
		if !ok1 {
			return vm.NIL, fmt.Errorf("ir/chunk-set-max-stack!: arg 1 must be Int, got %s", vs[1].Type().Name())
		}
		arg1 := int(arg1Int)
		arg0.SetMaxStack(arg1)
		return vm.NIL, nil
	})
	ns.Def("chunk-set-max-stack!", chunk_chunk_set_max_stack_bang_Fn)
	chunk_chunk_intern_const_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 2 {
			return vm.NIL, fmt.Errorf("ir/chunk-intern-const: expected (Self Value), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-intern-const: %v", err)
		}
		arg1 := vs[1]
		return vm.MakeInt(arg0.Consts().Intern(arg1)), nil
	})
	ns.Def("chunk-intern-const", chunk_chunk_intern_const_Fn)
	chunk_chunk_add_source_info_bang_Fn, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) {
		if len(vs) != 2 {
			return vm.NIL, fmt.Errorf("ir/chunk-add-source-info!: expected (Self BoxedAuxOrNil), got %d args", len(vs))
		}
		arg0, err := chunkFromBoxed(vs[0])
		if err != nil {
			return vm.NIL, fmt.Errorf("ir/chunk-add-source-info!: %v", err)
		}
		arg1Val := vs[1]
		var arg1 interface{}
		if arg1Val == vm.NIL {
			arg1 = nil
		} else if b, isBoxed := arg1Val.(*vm.Boxed); isBoxed {
			arg1 = b.Unbox()
		} else {
			arg1 = arg1Val
		}
		si, ok := arg1.(vm.SourceInfo)
		if !ok {
			// Allow boxed pointer too — accept either value or pointer.
			if siPtr, okp := arg1.(*vm.SourceInfo); okp {
				si = *siPtr
			} else {
				return vm.NIL, fmt.Errorf("ir/chunk-add-source-info!: arg 1 must be vm.SourceInfo, got %T", arg1)
			}
		}
		arg0.AddSourceInfo(si)
		return vm.NIL, nil
	})
	ns.Def("chunk-add-source-info!", chunk_chunk_add_source_info_bang_Fn)
	RegisterNS(ns)
}
