/*
 * Code generated by lginterop -primitives; DO NOT EDIT.
 */

package rt

import (
	"fmt"
	"github.com/nooga/let-go/pkg/vm"
)

func _adapt_Name(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 1 {
		return vm.NIL, fmt.Errorf("wrong number of args (%d), expected 1", len(vs))
	}
	a0 := vs[0]
	r, err := Name(a0)
	if err != nil {
		return vm.NIL, err
	}
	return vm.String(r), nil
}

func _adapt_UpperCase(vs []vm.Value) (vm.Value, error) {
	if len(vs) != 1 {
		return vm.NIL, fmt.Errorf("wrong number of args (%d), expected 1", len(vs))
	}
	a0 := vs[0]
	r, err := UpperCase(a0)
	if err != nil {
		return vm.NIL, err
	}
	return vm.String(r), nil
}

func _adapt_Subs(vs []vm.Value) (vm.Value, error) {
	switch len(vs) {
	case 2:
		return _adapt_Subs_arity2(vs)
	case 3:
		return _adapt_Subs3_arity3(vs)
	}
	return vm.NIL, fmt.Errorf("wrong number of args (%d)", len(vs))
}

func _adapt_Subs_arity2(vs []vm.Value) (vm.Value, error) {
	a0, ok := vs[0].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("expected string, got %s", vs[0].Type().Name())
	}
	a1, ok := vs[1].(vm.Int)
	if !ok {
		return vm.NIL, fmt.Errorf("expected int, got %s", vs[1].Type().Name())
	}
	r, err := Subs(string(a0), int(a1))
	if err != nil {
		return vm.NIL, err
	}
	return vm.String(r), nil
}

func _adapt_Subs3_arity3(vs []vm.Value) (vm.Value, error) {
	a0, ok := vs[0].(vm.String)
	if !ok {
		return vm.NIL, fmt.Errorf("expected string, got %s", vs[0].Type().Name())
	}
	a1, ok := vs[1].(vm.Int)
	if !ok {
		return vm.NIL, fmt.Errorf("expected int, got %s", vs[1].Type().Name())
	}
	a2, ok := vs[2].(vm.Int)
	if !ok {
		return vm.NIL, fmt.Errorf("expected int, got %s", vs[2].Type().Name())
	}
	r, err := Subs3(string(a0), int(a1), int(a2))
	if err != nil {
		return vm.NIL, err
	}
	return vm.String(r), nil
}

func _adapt_Nth(vs []vm.Value) (vm.Value, error) {
	switch len(vs) {
	case 2:
		return _adapt_Nth_arity2(vs)
	case 3:
		return _adapt_Nth3_arity3(vs)
	}
	return vm.NIL, fmt.Errorf("wrong number of args (%d)", len(vs))
}

func _adapt_Nth_arity2(vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	a1, ok := vs[1].(vm.Int)
	if !ok {
		return vm.NIL, fmt.Errorf("expected int, got %s", vs[1].Type().Name())
	}
	r, err := Nth(a0, int(a1))
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Nth3_arity3(vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	a1, ok := vs[1].(vm.Int)
	if !ok {
		return vm.NIL, fmt.Errorf("expected int, got %s", vs[1].Type().Name())
	}
	a2 := vs[2]
	r, err := Nth3(a0, int(a1), a2)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Deref(vs []vm.Value) (vm.Value, error) {
	switch len(vs) {
	case 1:
		return _adapt_Deref_arity1(vs)
	case 3:
		return _adapt_Deref3_arity3(vs)
	}
	return vm.NIL, fmt.Errorf("wrong number of args (%d)", len(vs))
}

func _adapt_Deref_arity1(vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	r, err := Deref(a0)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Deref3_arity3(vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	a1, ok := vs[1].(vm.Int)
	if !ok {
		return vm.NIL, fmt.Errorf("expected int, got %s", vs[1].Type().Name())
	}
	a2 := vs[2]
	r, err := Deref3(a0, int(a1), a2)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Str(vs []vm.Value) (vm.Value, error) {
	if len(vs) < 0 {
		return vm.NIL, fmt.Errorf("wrong number of args (%d), expected at least 0", len(vs))
	}
	r, err := Str(vs...)
	if err != nil {
		return vm.NIL, err
	}
	return vm.String(r), nil
}

func _adapt_Get(vs []vm.Value) (vm.Value, error) {
	switch len(vs) {
	case 2:
		return _adapt_Get_arity2(vs)
	case 3:
		return _adapt_Get3_arity3(vs)
	}
	return vm.NIL, fmt.Errorf("wrong number of args (%d)", len(vs))
}

func _adapt_Get_arity2(vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	a1 := vs[1]
	r, err := Get(a0, a1)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Get3_arity3(vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	a1 := vs[1]
	a2 := vs[2]
	r, err := Get3(a0, a1, a2)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Conj(vs []vm.Value) (vm.Value, error) {
	if len(vs) < 0 {
		return vm.NIL, fmt.Errorf("wrong number of args (%d), expected at least 0", len(vs))
	}
	r, err := Conj(vs...)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Reduce(ec *vm.ExecContext, vs []vm.Value) (vm.Value, error) {
	switch len(vs) {
	case 2:
		return _adapt_Reduce_arity2(ec, vs)
	case 3:
		return _adapt_Reduce3_arity3(ec, vs)
	}
	return vm.NIL, fmt.Errorf("wrong number of args (%d)", len(vs))
}

func _adapt_Reduce_arity2(ec *vm.ExecContext, vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	a1 := vs[1]
	r, err := Reduce(ec, a0, a1)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func _adapt_Reduce3_arity3(ec *vm.ExecContext, vs []vm.Value) (vm.Value, error) {
	a0 := vs[0]
	a1 := vs[1]
	a2 := vs[2]
	r, err := Reduce3(ec, a0, a1, a2)
	if err != nil {
		return vm.NIL, err
	}
	return r, nil
}

func RegisterGeneratedPrimitives() {
	RegisterNativeModule(&NativeModule{
		GoPkg:     "github.com/nooga/let-go/pkg/rt",
		Namespace: "clojure.core",
		Fns: map[string]NativeDirectFn{
			"name":     {GoIdent: "Name", LgName: "name", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "string", NeedsError: true},
			"subs@2":   {GoIdent: "Subs", LgName: "subs", Arity: 2, ParamSpecs: []string{"string", "int"}, ResultSpec: "string", NeedsError: true},
			"subs@3":   {GoIdent: "Subs3", LgName: "subs", Arity: 3, ParamSpecs: []string{"string", "int", "int"}, ResultSpec: "string", NeedsError: true},
			"nth@2":    {GoIdent: "Nth", LgName: "nth", Arity: 2, ParamSpecs: []string{"vm.Value", "int"}, ResultSpec: "vm.Value", NeedsError: true},
			"nth@3":    {GoIdent: "Nth3", LgName: "nth", Arity: 3, ParamSpecs: []string{"vm.Value", "int", "vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"deref@1":  {GoIdent: "Deref", LgName: "deref", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"deref@3":  {GoIdent: "Deref3", LgName: "deref", Arity: 3, ParamSpecs: []string{"vm.Value", "int", "vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"str":      {GoIdent: "Str", LgName: "str", Arity: -1, Variadic: true, ParamSpecs: []string{}, ResultSpec: "string", NeedsError: true},
			"get@2":    {GoIdent: "Get", LgName: "get", Arity: 2, ParamSpecs: []string{"vm.Value", "vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"get@3":    {GoIdent: "Get3", LgName: "get", Arity: 3, ParamSpecs: []string{"vm.Value", "vm.Value", "vm.Value"}, ResultSpec: "vm.Value", NeedsError: true},
			"conj":     {GoIdent: "Conj", LgName: "conj", Arity: -1, Variadic: true, ParamSpecs: []string{}, ResultSpec: "vm.Value", NeedsError: true},
			"reduce@2": {GoIdent: "Reduce", LgName: "reduce", Arity: 2, ParamSpecs: []string{"vm.Value", "vm.Value"}, ResultSpec: "vm.Value", NeedsError: true, NeedsEC: true},
			"reduce@3": {GoIdent: "Reduce3", LgName: "reduce", Arity: 3, ParamSpecs: []string{"vm.Value", "vm.Value", "vm.Value"}, ResultSpec: "vm.Value", NeedsError: true, NeedsEC: true},
		},
	})
	// Bind adapters into namespace
	if ns := LookupOrRegisterNSNoLoad("clojure.core"); ns != nil {
		fn0, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_Name(vs) })
		defGeneratedPrimitive(ns, "clojure.core", "name", fn0)
		fn1, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_Subs(vs) })
		defGeneratedPrimitive(ns, "clojure.core", "subs", fn1)
		fn2, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_Nth(vs) })
		defGeneratedPrimitive(ns, "clojure.core", "nth", fn2)
		fn3, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_Deref(vs) })
		defGeneratedPrimitive(ns, "clojure.core", "deref", fn3)
		fn4, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_Str(vs) })
		defGeneratedPrimitive(ns, "clojure.core", "str", fn4)
		fn5, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_Get(vs) })
		defGeneratedPrimitive(ns, "clojure.core", "get", fn5)
		fn6, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_Conj(vs) })
		defGeneratedPrimitive(ns, "clojure.core", "conj", fn6)
		defGeneratedPrimitive(ns, "clojure.core", "reduce", vm.NewCtxNativeFn("reduce", _adapt_Reduce))
	}
	RegisterNativeModule(&NativeModule{
		GoPkg:     "github.com/nooga/let-go/pkg/rt",
		Namespace: "clojure.string",
		Fns: map[string]NativeDirectFn{
			"upper-case": {GoIdent: "UpperCase", LgName: "upper-case", Arity: 1, ParamSpecs: []string{"vm.Value"}, ResultSpec: "string", NeedsError: true},
		},
	})
	// Bind adapters into namespace
	if ns := LookupOrRegisterNSNoLoad("clojure.string"); ns != nil {
		fn0, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_UpperCase(vs) })
		defGeneratedPrimitive(ns, "clojure.string", "upper-case", fn0)
	}
}
