package main

import (
	"fmt"
	"sort"
	"strings"
)

// targetPackagePath is the import path of the generated file's package (pkg/rt)
const targetPackagePath = "github.com/nooga/let-go/pkg/rt"

// isSamePackage returns true if the given GoPkg is the same as the target (rt)
func isSamePackage(goPkg string) bool {
	return goPkg == targetPackagePath
}

// emitFile generates the Go code for a set of primitive specs.
// It returns the formatted Go source code as a string.
// If specs is empty, it emits a valid stub with a no-op RegisterGeneratedPrimitives().
func emitFile(specs []primSpec) string {
	if len(specs) == 0 {
		// Empty stub: emit valid package with no-op registrar
		return `/*
 * Code generated by lginterop -primitives; DO NOT EDIT.
 */

package rt

func RegisterGeneratedPrimitives() {
}
`
	}

	var b strings.Builder

	// Collect unique GoPkg values to determine which packages need to be imported.
	// Skip packages that are the same as the target (rt) — no need to import ourselves.
	pkgAliasMap := make(map[string]string) // GoPkg -> alias (e.g. "github.com/nooga/let-go/pkg/rt/builtins" -> "builtins")
	for _, spec := range specs {
		if spec.GoPkg != "" && !isSamePackage(spec.GoPkg) && pkgAliasMap[spec.GoPkg] == "" {
			// Derive alias from last component of import path
			pkgAlias := spec.Package
			if pkgAlias == "" {
				// Fallback: extract from path
				lastSlash := strings.LastIndex(spec.GoPkg, "/")
				if lastSlash >= 0 {
					pkgAlias = spec.GoPkg[lastSlash+1:]
				} else {
					pkgAlias = spec.GoPkg
				}
			}
			pkgAliasMap[spec.GoPkg] = pkgAlias
		}
	}

	// Write header
	b.WriteString(`/*
 * Code generated by lginterop -primitives; DO NOT EDIT.
 */

package rt

import (
	"fmt"
	"github.com/nooga/let-go/pkg/vm"
`)

	// Add imports for scanned packages (excluding same-package). Emission order
	// here is irrelevant: the final file is run through gofmt (main.go), which
	// canonicalizes the import block. Registration STATEMENT order below is NOT
	// touched by gofmt, so that path sorts its keys explicitly.
	for goPkg := range pkgAliasMap {
		if !isSamePackage(goPkg) {
			fmt.Fprintf(&b, "\t%q\n", goPkg)
		}
	}

	b.WriteString(")\n\n")

	// Group specs by (Ns, LgName) to handle multi-arity
	lgNameGroups := groupSpecsByLgName(specs)

	// Generate adapter functions for each group (one per group, not per spec)
	for _, group := range lgNameGroups {
		if len(group) == 1 {
			// Single-arity: generate simple adapter
			b.WriteString(generateAdapter(&group[0], pkgAliasMap))
		} else {
			// Multi-arity: generate dispatch adapter (possibly ec-aware)
			b.WriteString(generateDispatchAdapter(group, pkgAliasMap))
		}
		b.WriteString("\n\n")
	}

	// Group specs by (Ns, GoPkg) to create NativeModule registrations
	moduleMap := groupSpecsByModule(specs)

	// Generate RegisterGeneratedPrimitives function
	b.WriteString("func RegisterGeneratedPrimitives() {\n")

	// Register each module in deterministic key order — Go map iteration is
	// randomized, so sort the (Ns|GoPkg) keys to keep regeneration byte-stable.
	moduleKeys := make([]string, 0, len(moduleMap))
	for k := range moduleMap {
		moduleKeys = append(moduleKeys, k)
	}
	sort.Strings(moduleKeys)
	for _, k := range moduleKeys {
		specs := moduleMap[k]
		if len(specs) > 0 {
			b.WriteString(generateModuleRegistration(specs, pkgAliasMap, lgNameGroups))
		}
	}

	b.WriteString("}\n")

	return b.String()
}

// groupSpecsByLgName groups specs by (Namespace, LgName) to handle multi-arity.
// Returns a slice of groups (each group is a slice of specs with same Ns and LgName).
func groupSpecsByLgName(specs []primSpec) [][]primSpec {
	lgNameMap := make(map[string][]primSpec)
	order := []string{} // Track order of first appearance

	for _, spec := range specs {
		key := spec.Ns + "|" + spec.LgName
		if lgNameMap[key] == nil {
			order = append(order, key)
		}
		lgNameMap[key] = append(lgNameMap[key], spec)
	}

	var result [][]primSpec
	for _, key := range order {
		result = append(result, lgNameMap[key])
	}
	return result
}

// groupSpecsByModule groups specs by (Namespace, GoPkg) to create NativeModule registrations.
func groupSpecsByModule(specs []primSpec) map[string][]primSpec {
	moduleMap := make(map[string][]primSpec)
	for _, spec := range specs {
		key := spec.Ns + "|" + spec.GoPkg
		moduleMap[key] = append(moduleMap[key], spec)
	}
	return moduleMap
}

// generateAdapter creates the adapter function for one spec.
func generateAdapter(spec *primSpec, pkgAliasMap map[string]string) string {
	var b strings.Builder

	pkgAlias := pkgAliasMap[spec.GoPkg]
	samePackage := isSamePackage(spec.GoPkg)

	// For NeedsEC functions, generate an ec-aware adapter
	if spec.NeedsEC {
		// Function signature: func _adapt_GoIdent(ec *vm.ExecContext, vs []vm.Value) (vm.Value, error)
		fmt.Fprintf(&b, "func _adapt_%s(ec *vm.ExecContext, vs []vm.Value) (vm.Value, error) {\n", spec.GoIdent)

		// Check arity
		if spec.Variadic {
			fmt.Fprintf(&b, "\tif len(vs) < %d { return vm.NIL, fmt.Errorf(\"wrong number of args (%%d), expected at least %d\", len(vs)) }\n",
				len(spec.ParamSpecs), len(spec.ParamSpecs))
		} else if spec.Arity >= 0 {
			fmt.Fprintf(&b, "\tif len(vs) != %d { return vm.NIL, fmt.Errorf(\"wrong number of args (%%d), expected %d\", len(vs)) }\n",
				spec.Arity, spec.Arity)
		}

		// Generate parameter coercions
		for i, paramSpec := range spec.ParamSpecs {
			varName := fmt.Sprintf("a%d", i)
			b.WriteString(generateParamCoercion(varName, i, paramSpec))
		}

		// Build the function call
		fmt.Fprintf(&b, "\t")

		// If we need to handle the return value, prepare for it
		if spec.ResultSpec != "" {
			if spec.NeedsError {
				fmt.Fprintf(&b, "r, err := ")
			} else {
				fmt.Fprintf(&b, "r := ")
			}
		} else if spec.NeedsError {
			fmt.Fprintf(&b, "_, err := ")
		}

		// Call the actual function: unqualified for same package, qualified otherwise
		if samePackage {
			fmt.Fprintf(&b, "%s(ec", spec.GoIdent)
		} else {
			fmt.Fprintf(&b, "%s.%s(ec", pkgAlias, spec.GoIdent)
		}

		// Add parameters
		for i, paramSpec := range spec.ParamSpecs {
			b.WriteString(", ")
			// Cast to the actual Go type if needed
			switch paramSpec {
			case "string":
				fmt.Fprintf(&b, "string(a%d)", i)
			case "int", "int64", "float64":
				fmt.Fprintf(&b, "%s(a%d)", paramSpec, i)
			case "bool":
				fmt.Fprintf(&b, "bool(a%d)", i)
			default:
				// For types like vm.Value, *Foo, etc., use as-is
				fmt.Fprintf(&b, "a%d", i)
			}
		}
		b.WriteString(")\n")

		// Handle error if needed
		if spec.NeedsError {
			b.WriteString("\tif err != nil { return vm.NIL, err }\n")
		}

		// Box and return the result
		if spec.ResultSpec != "" {
			b.WriteString(generateResultBoxing(spec.ResultSpec))
		} else {
			b.WriteString("\treturn vm.NIL, nil\n")
		}

		b.WriteString("}")
	} else {
		// Non-EC adapter: standard signature
		// Function signature: func _adapt_GoIdent(vs []vm.Value) (vm.Value, error)
		fmt.Fprintf(&b, "func _adapt_%s(vs []vm.Value) (vm.Value, error) {\n", spec.GoIdent)

		// Check arity
		if spec.Variadic {
			fmt.Fprintf(&b, "\tif len(vs) < %d { return vm.NIL, fmt.Errorf(\"wrong number of args (%%d), expected at least %d\", len(vs)) }\n",
				len(spec.ParamSpecs), len(spec.ParamSpecs))
		} else if spec.Arity >= 0 {
			fmt.Fprintf(&b, "\tif len(vs) != %d { return vm.NIL, fmt.Errorf(\"wrong number of args (%%d), expected %d\", len(vs)) }\n",
				spec.Arity, spec.Arity)
		}

		// For non-variadic functions, generate parameter coercions
		// For variadic functions, just pass all vs values
		if spec.Variadic {
			// Build the function call - pass all arguments
			fmt.Fprintf(&b, "\t")

			// If we need to handle the return value, prepare for it
			if spec.ResultSpec != "" {
				if spec.NeedsError {
					fmt.Fprintf(&b, "r, err := ")
				} else {
					fmt.Fprintf(&b, "r := ")
				}
			} else if spec.NeedsError {
				fmt.Fprintf(&b, "_, err := ")
			}

			// Call the actual function: unqualified for same package, qualified otherwise
			if samePackage {
				fmt.Fprintf(&b, "%s(vs...)\n", spec.GoIdent)
			} else {
				fmt.Fprintf(&b, "%s.%s(vs...)\n", pkgAlias, spec.GoIdent)
			}
		} else {
			// Non-variadic: generate parameter coercions
			for i, paramSpec := range spec.ParamSpecs {
				varName := fmt.Sprintf("a%d", i)
				b.WriteString(generateParamCoercion(varName, i, paramSpec))
			}

			// Build the function call
			fmt.Fprintf(&b, "\t")

			// If we need to handle the return value, prepare for it
			if spec.ResultSpec != "" {
				if spec.NeedsError {
					fmt.Fprintf(&b, "r, err := ")
				} else {
					fmt.Fprintf(&b, "r := ")
				}
			} else if spec.NeedsError {
				fmt.Fprintf(&b, "_, err := ")
			}

			// Call the actual function: unqualified for same package, qualified otherwise
			if samePackage {
				fmt.Fprintf(&b, "%s(", spec.GoIdent)
			} else {
				fmt.Fprintf(&b, "%s.%s(", pkgAlias, spec.GoIdent)
			}

			// Add parameters
			for i, paramSpec := range spec.ParamSpecs {
				if i > 0 {
					b.WriteString(", ")
				}
				// Cast to the actual Go type if needed
				switch paramSpec {
				case "string":
					fmt.Fprintf(&b, "string(a%d)", i)
				case "int", "int64", "float64":
					fmt.Fprintf(&b, "%s(a%d)", paramSpec, i)
				case "bool":
					fmt.Fprintf(&b, "bool(a%d)", i)
				default:
					// For types like vm.Value, *Foo, etc., use as-is
					fmt.Fprintf(&b, "a%d", i)
				}
			}
			b.WriteString(")\n")
		}

		// Handle error if needed
		if spec.NeedsError {
			b.WriteString("\tif err != nil { return vm.NIL, err }\n")
		}

		// Box and return the result
		if spec.ResultSpec != "" {
			b.WriteString(generateResultBoxing(spec.ResultSpec))
		} else {
			b.WriteString("\treturn vm.NIL, nil\n")
		}

		b.WriteString("}")
	}

	return b.String()
}

// generateDispatchAdapter creates a multi-arity dispatch adapter for specs with the same (Ns, LgName).
// It emits one adapter that switches on len(vs) and calls the appropriate arity-specific adapter.
// If any spec in the group needs EC, all adapters (dispatch and arity-specific) are EC-aware.
func generateDispatchAdapter(group []primSpec, pkgAliasMap map[string]string) string {
	if len(group) <= 1 {
		// Should not happen, but fallback to simple adapter
		if len(group) == 1 {
			return generateAdapter(&group[0], pkgAliasMap)
		}
		return ""
	}

	// Check if any spec in the group needs EC
	groupNeedsEC := false
	for _, spec := range group {
		if spec.NeedsEC {
			groupNeedsEC = true
			break
		}
	}

	// Use the first spec's LgName and Namespace for the dispatch adapter name
	spec0 := group[0]
	dispatchAdapterName := fmt.Sprintf("_adapt_%s", spec0.GoIdent)

	var b strings.Builder

	// Dispatch adapter signature depends on groupNeedsEC
	if groupNeedsEC {
		fmt.Fprintf(&b, "func %s(ec *vm.ExecContext, vs []vm.Value) (vm.Value, error) {\n", dispatchAdapterName)
	} else {
		fmt.Fprintf(&b, "func %s(vs []vm.Value) (vm.Value, error) {\n", dispatchAdapterName)
	}
	fmt.Fprintf(&b, "\tswitch len(vs) {\n")

	// Sort by arity for deterministic output
	sort.Slice(group, func(i, j int) bool {
		ai := group[i].Arity
		if ai == -1 {
			ai = 9999 // variadic last
		}
		aj := group[j].Arity
		if aj == -1 {
			aj = 9999
		}
		return ai < aj
	})

	for _, spec := range group {
		if spec.Arity == -1 {
			// Variadic: "default" case
			fmt.Fprintf(&b, "\tdefault:\n")
			fmt.Fprintf(&b, "\t\tif len(vs) >= %d {\n", len(spec.ParamSpecs))
			if groupNeedsEC {
				fmt.Fprintf(&b, "\t\t\treturn _adapt_%s_arity%d(ec, vs)\n", spec.GoIdent, len(spec.ParamSpecs))
			} else {
				fmt.Fprintf(&b, "\t\t\treturn _adapt_%s_arity%d(vs)\n", spec.GoIdent, len(spec.ParamSpecs))
			}
			fmt.Fprintf(&b, "\t\t}\n")
		} else {
			// Fixed arity
			fmt.Fprintf(&b, "\tcase %d:\n", spec.Arity)
			if groupNeedsEC {
				fmt.Fprintf(&b, "\t\treturn _adapt_%s_arity%d(ec, vs)\n", spec.GoIdent, spec.Arity)
			} else {
				fmt.Fprintf(&b, "\t\treturn _adapt_%s_arity%d(vs)\n", spec.GoIdent, spec.Arity)
			}
		}
	}

	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn vm.NIL, fmt.Errorf(\"wrong number of args (%%d)\", len(vs))\n")
	fmt.Fprintf(&b, "}\n")

	// Generate the arity-specific adapters
	var adapters strings.Builder
	for _, spec := range group {
		arity := spec.Arity
		if arity == -1 {
			arity = len(spec.ParamSpecs)
		}
		adapters.WriteString(generateAritySpecificAdapter(&spec, arity, pkgAliasMap, groupNeedsEC))
		adapters.WriteString("\n\n")
	}

	return b.String() + "\n" + adapters.String()
}

// generateAritySpecificAdapter generates an adapter for a specific arity variant.
// The adapter name includes the arity suffix, e.g., _adapt_Foo_arity2.
// If groupNeedsEC, all arity-specific adapters take (ec *vm.ExecContext, vs []vm.Value) signature.
func generateAritySpecificAdapter(spec *primSpec, arity int, pkgAliasMap map[string]string, groupNeedsEC bool) string {
	var b strings.Builder

	pkgAlias := pkgAliasMap[spec.GoPkg]
	samePackage := isSamePackage(spec.GoPkg)

	// Function signature depends on groupNeedsEC
	if groupNeedsEC {
		fmt.Fprintf(&b, "func _adapt_%s_arity%d(ec *vm.ExecContext, vs []vm.Value) (vm.Value, error) {\n", spec.GoIdent, arity)
	} else {
		fmt.Fprintf(&b, "func _adapt_%s_arity%d(vs []vm.Value) (vm.Value, error) {\n", spec.GoIdent, arity)
	}

	// No arity check here; the dispatch adapter already validated it

	// For non-variadic functions, generate parameter coercions
	// For variadic functions, just pass required params + remaining args as variadic
	if spec.Variadic {
		// For variadic functions:
		// - Generate coercions for required parameters (ParamSpecs)
		// - Pass remaining arguments as the variadic part

		// Generate parameter coercions for required params
		for i, paramSpec := range spec.ParamSpecs {
			varName := fmt.Sprintf("a%d", i)
			b.WriteString(generateParamCoercion(varName, i, paramSpec))
		}

		// Build the function call
		fmt.Fprintf(&b, "\t")

		// If we need to handle the return value, prepare for it
		if spec.ResultSpec != "" {
			if spec.NeedsError {
				fmt.Fprintf(&b, "r, err := ")
			} else {
				fmt.Fprintf(&b, "r := ")
			}
		} else if spec.NeedsError {
			fmt.Fprintf(&b, "_, err := ")
		}

		// Call the actual function: unqualified for same package, qualified otherwise
		if samePackage {
			fmt.Fprintf(&b, "%s(", spec.GoIdent)
		} else {
			fmt.Fprintf(&b, "%s.%s(", pkgAlias, spec.GoIdent)
		}

		// Add ExecContext if needed
		if spec.NeedsEC {
			b.WriteString("ec")
			if len(spec.ParamSpecs) > 0 {
				b.WriteString(", ")
			}
		}

		// Add required parameters
		for i := range spec.ParamSpecs {
			if i > 0 {
				b.WriteString(", ")
			}
			varName := fmt.Sprintf("a%d", i)
			fmt.Fprintf(&b, "%s", varName)
		}

		// Add variadic arguments: pass remaining vs elements
		if len(spec.ParamSpecs) > 0 {
			fmt.Fprintf(&b, ", vs[%d:]...\n", len(spec.ParamSpecs))
		} else {
			b.WriteString("vs...\n")
		}
	} else {
		// Non-variadic: standard parameter coercion
		// Generate parameter coercions
		for i, paramSpec := range spec.ParamSpecs {
			varName := fmt.Sprintf("a%d", i)
			b.WriteString(generateParamCoercion(varName, i, paramSpec))
		}

		// Build the function call
		fmt.Fprintf(&b, "\t")

		// If we need to handle the return value, prepare for it
		if spec.ResultSpec != "" {
			if spec.NeedsError {
				fmt.Fprintf(&b, "r, err := ")
			} else {
				fmt.Fprintf(&b, "r := ")
			}
		} else if spec.NeedsError {
			fmt.Fprintf(&b, "_, err := ")
		}

		// Call the actual function: unqualified for same package, qualified otherwise
		if samePackage {
			fmt.Fprintf(&b, "%s(", spec.GoIdent)
		} else {
			fmt.Fprintf(&b, "%s.%s(", pkgAlias, spec.GoIdent)
		}

		// Add ExecContext if needed. In a groupNeedsEC dispatcher a non-NeedsEC
		// spec simply doesn't reference ec (the dispatcher still receives it),
		// so there's nothing to emit here for that case.
		if spec.NeedsEC {
			b.WriteString("ec")
			if len(spec.ParamSpecs) > 0 {
				b.WriteString(", ")
			}
		}

		// Add parameters
		for i, paramSpec := range spec.ParamSpecs {
			if i > 0 {
				b.WriteString(", ")
			}
			// Cast to the actual Go type if needed
			switch paramSpec {
			case "string":
				fmt.Fprintf(&b, "string(a%d)", i)
			case "int", "int64", "float64":
				fmt.Fprintf(&b, "%s(a%d)", paramSpec, i)
			case "bool":
				fmt.Fprintf(&b, "bool(a%d)", i)
			default:
				// For types like vm.Value, *Foo, etc., use as-is
				fmt.Fprintf(&b, "a%d", i)
			}
		}
		b.WriteString(")\n")
	}

	// If groupNeedsEC but this spec doesn't need it, add a statement to suppress unused parameter warning
	if groupNeedsEC && !spec.NeedsEC {
		b.WriteString("\t_ = ec\n")
	}

	// Handle error if needed
	if spec.NeedsError {
		b.WriteString("\tif err != nil { return vm.NIL, err }\n")
	}

	// Box and return the result
	if spec.ResultSpec != "" {
		b.WriteString(generateResultBoxing(spec.ResultSpec))
	} else {
		b.WriteString("\treturn vm.NIL, nil\n")
	}

	b.WriteString("}")

	return b.String()
}

// generateParamCoercion generates the type coercion code for one parameter.
func generateParamCoercion(varName string, index int, paramSpec string) string {
	var b strings.Builder

	switch paramSpec {
	case "string":
		fmt.Fprintf(&b, "\t%s, ok := vs[%d].(vm.String)\n", varName, index)
		fmt.Fprintf(&b, "\tif !ok { return vm.NIL, fmt.Errorf(\"expected string, got %%s\", vs[%d].Type().Name()) }\n", index)
	case "int":
		fmt.Fprintf(&b, "\t%s, ok := vs[%d].(vm.Int)\n", varName, index)
		fmt.Fprintf(&b, "\tif !ok { return vm.NIL, fmt.Errorf(\"expected int, got %%s\", vs[%d].Type().Name()) }\n", index)
	case "int64":
		fmt.Fprintf(&b, "\t%s, ok := vs[%d].(vm.Int)\n", varName, index)
		fmt.Fprintf(&b, "\tif !ok { return vm.NIL, fmt.Errorf(\"expected int64, got %%s\", vs[%d].Type().Name()) }\n", index)
	case "float64":
		fmt.Fprintf(&b, "\t%s, ok := vs[%d].(vm.Float)\n", varName, index)
		fmt.Fprintf(&b, "\tif !ok { return vm.NIL, fmt.Errorf(\"expected float64, got %%s\", vs[%d].Type().Name()) }\n", index)
	case "bool":
		fmt.Fprintf(&b, "\t%s, ok := vs[%d].(vm.Boolean)\n", varName, index)
		fmt.Fprintf(&b, "\tif !ok { return vm.NIL, fmt.Errorf(\"expected bool, got %%s\", vs[%d].Type().Name()) }\n", index)
	case "vm.Value":
		fmt.Fprintf(&b, "\t%s := vs[%d]\n", varName, index)
	default:
		// For other types (e.g., *Foo, vm.String, etc.), use direct assignment with type assertion
		fmt.Fprintf(&b, "\t%s, ok := vs[%d].(%s)\n", varName, index, paramSpec)
		fmt.Fprintf(&b, "\tif !ok { return vm.NIL, fmt.Errorf(\"expected %s, got %%s\", vs[%d].Type().Name()) }\n", paramSpec, index)
	}

	return b.String()
}

// generateResultBoxing generates code to box the result.
func generateResultBoxing(resultSpec string) string {
	switch resultSpec {
	case "string":
		return "\treturn vm.String(r), nil\n"
	case "int", "int64":
		return "\treturn vm.Int(r), nil\n"
	case "float64":
		return "\treturn vm.Float(r), nil\n"
	case "bool":
		return "\treturn vm.Boolean(r), nil\n"
	case "vm.Value":
		return "\treturn r, nil\n"
	default:
		// For other types, assume they're already vm.Value or can be cast
		return fmt.Sprintf("\treturn %s(r), nil\n", resultSpec)
	}
}

// generateModuleRegistration creates the RegisterNativeModule call for a group of specs.
func generateModuleRegistration(specs []primSpec, pkgAliasMap map[string]string, lgNameGroups [][]primSpec) string {
	if len(specs) == 0 {
		return ""
	}

	var b strings.Builder

	// Get the namespace and Go package from the first spec (all in group share these)
	ns := specs[0].Ns
	goPkg := specs[0].GoPkg

	fmt.Fprintf(&b, "\tRegisterNativeModule(&NativeModule{\n")
	fmt.Fprintf(&b, "\t\tGoPkg:     %q,\n", goPkg)
	fmt.Fprintf(&b, "\t\tNamespace: %q,\n", ns)
	fmt.Fprintf(&b, "\t\tFns: map[string]NativeDirectFn{\n")

	// Group specs by (Ns, LgName) to emit one entry per arity per LgName
	lgNameMap := make(map[string][]primSpec)
	order := []string{} // Track order of first appearance

	for _, spec := range specs {
		key := spec.Ns + "|" + spec.LgName
		if lgNameMap[key] == nil {
			order = append(order, key)
		}
		lgNameMap[key] = append(lgNameMap[key], spec)
	}

	for _, key := range order {
		group := lgNameMap[key]
		if len(group) == 1 {
			// Single-arity: one entry with the LgName
			b.WriteString(generateNativeDirectFnEntry(&group[0], false))
		} else {
			// Multi-arity: emit entries for each arity
			// Sort by arity
			sort.Slice(group, func(i, j int) bool {
				ai := group[i].Arity
				if ai == -1 {
					ai = 9999
				}
				aj := group[j].Arity
				if aj == -1 {
					aj = 9999
				}
				return ai < aj
			})
			for _, spec := range group {
				b.WriteString(generateNativeDirectFnEntry(&spec, true))
			}
		}
	}

	b.WriteString("\t\t},\n")
	b.WriteString("\t})\n")

	// Bind functions into the namespace at runtime
	// Group specs by LgName to identify multi-arity vs single-arity
	lgNameBindMap := make(map[string][]primSpec)
	orderBind := []string{} // Track order of first appearance
	for _, spec := range specs {
		key := spec.LgName
		if lgNameBindMap[key] == nil {
			orderBind = append(orderBind, key)
		}
		lgNameBindMap[key] = append(lgNameBindMap[key], spec)
	}

	// Emit namespace bindings. Use the NoLoad variant: this runs during rt
	// init (RegisterGeneratedPrimitives), and we only need to get-or-create the
	// target ns to Def adapters into it — NOT trigger its source load. Under the
	// precompiled bundle the ns is already loaded so it made no difference, but
	// in source-stdlib bootstrap the loading variant forced a premature compile
	// of the ns before the compiler was ready, corrupting it (e.g. `string`'s
	// `join` never interned → `s/join` failed to resolve). The real source load
	// happens later, when user code actually requires the ns.
	fmt.Fprintf(&b, "\t// Bind adapters into namespace\n")
	fmt.Fprintf(&b, "\tif ns := LookupOrRegisterNSNoLoad(%q); ns != nil {\n", ns)
	for i, lgName := range orderBind {
		group := lgNameBindMap[lgName]
		// Check if this group needs EC
		groupNeedsEC := false
		for _, spec := range group {
			if spec.NeedsEC {
				groupNeedsEC = true
				break
			}
		}

		// defGeneratedPrimitive (not a bare ns.Def) records the binding so
		// the runtime can reapply it after the namespace's on-demand source
		// load re-Defs bootstrap closures over the native adapter.
		if groupNeedsEC {
			// EC-aware: register via vm.NewCtxNativeFn directly (don't wrap with NativeFnType)
			fmt.Fprintf(&b, "\t\tdefGeneratedPrimitive(ns, %q, %q, vm.NewCtxNativeFn(%q, _adapt_%s))\n", ns, lgName, lgName, group[0].GoIdent)
		} else {
			// Non-EC: wrap with NativeFnType
			fmt.Fprintf(&b, "\t\tfn%d, _ := vm.NativeFnType.Wrap(func(vs []vm.Value) (vm.Value, error) { return _adapt_%s(vs) })\n", i, group[0].GoIdent)
			fmt.Fprintf(&b, "\t\tdefGeneratedPrimitive(ns, %q, %q, fn%d)\n", ns, lgName, i)
		}
	}
	b.WriteString("\t}\n")

	return b.String()
}

// generateNativeDirectFnEntry creates one map entry for a NativeDirectFn.
// If isMultiArity is true, the key includes the arity to distinguish multiple arities of the same name.
func generateNativeDirectFnEntry(spec *primSpec, isMultiArity bool) string {
	var b strings.Builder

	// For multi-arity, include arity in the key to avoid duplicate keys in the map.
	// Key format: "name" for single-arity, "name@arity" for multi-arity (registry keyed by [ns name arity]).
	var registryKey string
	if isMultiArity {
		if spec.Arity == -1 {
			registryKey = fmt.Sprintf("%s@variadic", spec.LgName)
		} else {
			registryKey = fmt.Sprintf("%s@%d", spec.LgName, spec.Arity)
		}
	} else {
		registryKey = spec.LgName
	}

	fmt.Fprintf(&b, "\t\t\t%q: {GoIdent: %q, LgName: %q, Arity: %d",
		registryKey, spec.GoIdent, spec.LgName, spec.Arity)

	if spec.Variadic {
		b.WriteString(", Variadic: true")
	}

	fmt.Fprintf(&b, ", ParamSpecs: []string{")
	for i, ps := range spec.ParamSpecs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", ps)
	}
	b.WriteString("}")

	fmt.Fprintf(&b, ", ResultSpec: %q", spec.ResultSpec)

	if spec.NeedsError {
		b.WriteString(", NeedsError: true")
	}

	if spec.NeedsEC {
		b.WriteString(", NeedsEC: true")
	}

	b.WriteString("},\n")

	return b.String()
}
