// Code generated by lgbgen --target=go. DO NOT EDIT.

//go:build gogen_ir

package wasmhost

import (
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/core"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/edn"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/graph"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/hash"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/io"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/build"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/data/generated"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/dominance"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/dump"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/lattice"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/lower"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/lower_go"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/ops"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/constfold"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/cse"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/dce"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/infer_arg_types"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/licm"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/mutability"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/pipeline"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/trace"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/passes/typeinfer"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/structurize"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/ir/validate"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/pprint"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/test"
	_ "github.com/nooga/let-go/pkg/rt/core_go_lowered/walk"
)
